package db

import (
	"cattleai/ent"
	"time"
)

const DefaultTenant = "system_tenant"

var apis = []ent.API{
	{
		ID:        1,
		Name:      "首页",
		Path:      "/",
		Level:     1,
		Hash:      "index",
		Redirect:  "/index",
		Component: "/layouts/main",
		IsSub:     false,
		HasSub:    false,
		Single:    false,
		ParentId:  -1,
		TenantId:  DefaultTenant,
		CreatedAt: time.Now().Unix(),
		UpdatedAt: time.Now().Unix(),
		Deleted:   0,
	},
	{
		ID:        2,
		Name:      "信息登记",
		Path:      "/registration",
		Level:     1,
		Hash:      "registration",
		Redirect:  "/registration/farminfo/farmreg",
		Component: "/layouts/main",
		IsSub:     false,
		HasSub:    true,
		Single:    false,
		ParentId:  -1,
		TenantId:  DefaultTenant,
		CreatedAt: time.Now().Unix(),
		UpdatedAt: time.Now().Unix(),
		Deleted:   0,
	},
	{
		ID:        3,
		Name:      "信息查询",
		Path:      "/informations",
		Level:     1,
		Hash:      "informations",
		Redirect:  "/informations/farminfo/farmreg",
		Component: "/layouts/main",
		IsSub:     false,
		HasSub:    true,
		Single:    false,
		ParentId:  -1,
		TenantId:  DefaultTenant,
		CreatedAt: time.Now().Unix(),
		UpdatedAt: time.Now().Unix(),
		Deleted:   0,
	},
	{
		ID:        4,
		Name:      "生产管理",
		Path:      "/pm",
		Level:     1,
		Hash:      "pm",
		Redirect:  "/pm/farminfo/farmreg",
		Component: "/layouts/main",
		IsSub:     false,
		HasSub:    true,
		Single:    false,
		ParentId:  -1,
		TenantId:  DefaultTenant,
		CreatedAt: time.Now().Unix(),
		UpdatedAt: time.Now().Unix(),
		Deleted:   0,
	},
	{
		ID:        5,
		Name:      "屠宰分割",
		Path:      "/slaughter",
		Level:     1,
		Hash:      "slaughter",
		Redirect:  "/slaughter/farminfo/farmreg",
		Component: "/layouts/main",
		IsSub:     false,
		HasSub:    true,
		Single:    false,
		ParentId:  -1,
		TenantId:  DefaultTenant,
		CreatedAt: time.Now().Unix(),
		UpdatedAt: time.Now().Unix(),
		Deleted:   0,
	},
	{
		ID:        6,
		Name:      "财务管理",
		Path:      "/financial",
		Level:     1,
		Hash:      "financial",
		Redirect:  "/financial/farminfo/farmreg",
		Component: "/layouts/main",
		IsSub:     false,
		HasSub:    true,
		Single:    false,
		ParentId:  -1,
		TenantId:  DefaultTenant,
		CreatedAt: time.Now().Unix(),
		UpdatedAt: time.Now().Unix(),
		Deleted:   0,
	},
	{
		ID:        7,
		Name:      "信息统计",
		Path:      "/statistics",
		Level:     1,
		Hash:      "statistics",
		Redirect:  "/statistics/farminfo/farmreg",
		Component: "/layouts/main",
		IsSub:     false,
		HasSub:    true,
		Single:    false,
		ParentId:  -1,
		TenantId:  DefaultTenant,
		CreatedAt: time.Now().Unix(),
		UpdatedAt: time.Now().Unix(),
		Deleted:   0,
	},
	{
		ID:        8,
		Name:      "分析报表",
		Path:      "/analysis",
		Level:     1,
		Hash:      "analysis",
		Redirect:  "/analysis/farminfo/farmreg",
		Component: "/layouts/main",
		IsSub:     false,
		HasSub:    true,
		Single:    false,
		ParentId:  -1,
		TenantId:  DefaultTenant,
		CreatedAt: time.Now().Unix(),
		UpdatedAt: time.Now().Unix(),
		Deleted:   0,
	},
	{
		ID:        9,
		Name:      "基础资料",
		Path:      "/basics",
		Level:     1,
		Hash:      "basics",
		Redirect:  "/basics/farminfo/farmreg",
		Component: "/layouts/main",
		IsSub:     false,
		HasSub:    true,
		Single:    false,
		ParentId:  -1,
		TenantId:  DefaultTenant,
		CreatedAt: time.Now().Unix(),
		UpdatedAt: time.Now().Unix(),
		Deleted:   0,
	},
	{
		ID:        91,
		Name:      "系统设置",
		Path:      "/settings",
		Level:     1,
		Hash:      "settings",
		Redirect:  "/settings/tenants",
		Component: "/layouts/main",
		IsSub:     false,
		HasSub:    true,
		Single:    false,
		ParentId:  -1,
		TenantId:  DefaultTenant,
		CreatedAt: time.Now().Unix(),
		UpdatedAt: time.Now().Unix(),
		Deleted:   0,
	},
	{
		ID:        911,
		Name:      "租户设置",
		Path:      "/settings/tenants",
		Level:     2,
		Hash:      "settings",
		Component: "/layouts/sub",
		IsSub:     false,
		HasSub:    false,
		Single:    false,
		ParentId:  91,
		TenantId:  DefaultTenant,
		CreatedAt: time.Now().Unix(),
		UpdatedAt: time.Now().Unix(),
		Deleted:   0,
	},

	// 信息登记子菜单
	{
		ID:        10,
		Name:      "牛场信息",
		Path:      "/registration/farminfo",
		Level:     2,
		Hash:      "registration",
		Redirect:  "",
		Component: "/layouts/sub",
		IsSub:     true,
		HasSub:    false,
		Single:    false,
		ParentId:  2,
		TenantId:  DefaultTenant,
		CreatedAt: time.Now().Unix(),
		UpdatedAt: time.Now().Unix(),
		Deleted:   0,
	},
	{
		ID:        11,
		Name:      "个体识别",
		Path:      "/registration/cattle",
		Level:     2,
		Hash:      "registration",
		Redirect:  "",
		Component: "/layouts/sub",
		IsSub:     true,
		HasSub:    false,
		Single:    true,
		ParentId:  2,
		TenantId:  DefaultTenant,
		CreatedAt: time.Now().Unix(),
		UpdatedAt: time.Now().Unix(),
		Deleted:   0,
	},
	{
		ID:        12,
		Name:      "生长效率",
		Path:      "/registration/growspanel",
		Level:     2,
		Hash:      "registration",
		Redirect:  "",
		Component: "/layouts/sub",
		IsSub:     true,
		HasSub:    false,
		Single:    false,
		ParentId:  2,
		TenantId:  DefaultTenant,
		CreatedAt: time.Now().Unix(),
		UpdatedAt: time.Now().Unix(),
		Deleted:   0,
	},
	{
		ID:        13,
		Name:      "繁殖状况",
		Path:      "/registration/reproductions",
		Level:     2,
		Hash:      "registration",
		Redirect:  "",
		Component: "/layouts/sub",
		IsSub:     true,
		HasSub:    false,
		Single:    false,
		ParentId:  2,
		TenantId:  DefaultTenant,
		CreatedAt: time.Now().Unix(),
		UpdatedAt: time.Now().Unix(),
		Deleted:   0,
	},
	{
		ID:        14,
		Name:      "疫病防控",
		Path:      "/registration/epidemicspannel",
		Level:     2,
		Hash:      "registration",
		Redirect:  "",
		Component: "/layouts/sub",
		IsSub:     true,
		HasSub:    false,
		Single:    false,
		ParentId:  2,
		TenantId:  DefaultTenant,
		CreatedAt: time.Now().Unix(),
		UpdatedAt: time.Now().Unix(),
		Deleted:   0,
	},
	{
		ID:        15,
		Name:      "物料管理",
		Path:      "/registration/materials",
		Level:     2,
		Hash:      "registration",
		Redirect:  "",
		Component: "/layouts/sub",
		IsSub:     true,
		HasSub:    false,
		Single:    false,
		ParentId:  2,
		TenantId:  DefaultTenant,
		CreatedAt: time.Now().Unix(),
		UpdatedAt: time.Now().Unix(),
		Deleted:   0,
	},
	{
		ID:        16,
		Name:      "饲喂管理",
		Path:      "/registration/feedingmgr",
		Level:     2,
		Hash:      "registration",
		Redirect:  "",
		Component: "/layouts/sub",
		IsSub:     true,
		HasSub:    false,
		Single:    false,
		ParentId:  2,
		TenantId:  DefaultTenant,
		CreatedAt: time.Now().Unix(),
		UpdatedAt: time.Now().Unix(),
		Deleted:   0,
	},
	{
		ID:        17,
		Name:      "牛群异动",
		Path:      "/registration/cattlegroups",
		Level:     2,
		Hash:      "registration",
		Redirect:  "",
		Component: "/layouts/sub",
		IsSub:     true,
		HasSub:    false,
		Single:    false,
		ParentId:  2,
		TenantId:  DefaultTenant,
		CreatedAt: time.Now().Unix(),
		UpdatedAt: time.Now().Unix(),
		Deleted:   0,
	},
	{
		ID:        18,
		Name:      "屠宰分割",
		Path:      "/registration/slaughter",
		Level:     2,
		Hash:      "registration",
		Redirect:  "",
		Component: "/layouts/sub",
		IsSub:     true,
		HasSub:    false,
		Single:    false,
		ParentId:  2,
		TenantId:  DefaultTenant,
		CreatedAt: time.Now().Unix(),
		UpdatedAt: time.Now().Unix(),
		Deleted:   0,
	},
	{
		ID:        19,
		Name:      "批量导入",
		Path:      "/registration/batchimport",
		Level:     2,
		Hash:      "registration",
		Redirect:  "",
		Component: "/layouts/sub",
		IsSub:     true,
		HasSub:    false,
		Single:    true,
		ParentId:  2,
		TenantId:  DefaultTenant,
		CreatedAt: time.Now().Unix(),
		UpdatedAt: time.Now().Unix(),
		Deleted:   0,
	},

	// 牛场信息子菜单
	{
		ID:        101,
		Name:      "牛场录入",
		Path:      "/registration/farminfo/farmreg",
		Level:     3,
		Hash:      "registration",
		Redirect:  "",
		Component: "/pages/regs/farmreg",
		IsSub:     false,
		HasSub:    false,
		Single:    false,
		ParentId:  10,
		TenantId:  DefaultTenant,
		CreatedAt: time.Now().Unix(),
		UpdatedAt: time.Now().Unix(),
		Deleted:   0,
	},
	{
		ID:        102,
		Name:      "牛舍录入",
		Path:      "/registration/farminfo/cattleshedreg",
		Level:     3,
		Hash:      "registration",
		Redirect:  "",
		Component: "/pages/regs/cattleshedreg",
		IsSub:     false,
		HasSub:    false,
		Single:    false,
		ParentId:  10,
		TenantId:  DefaultTenant,
		CreatedAt: time.Now().Unix(),
		UpdatedAt: time.Now().Unix(),
		Deleted:   0,
	},
	{
		ID:        103,
		Name:      "生产环境",
		Path:      "/registration/farminfo/surroundingreg",
		Level:     3,
		Hash:      "registration",
		Redirect:  "",
		Component: "/pages/regs/surrounding",
		IsSub:     false,
		HasSub:    false,
		Single:    false,
		ParentId:  10,
		TenantId:  DefaultTenant,
		CreatedAt: time.Now().Unix(),
		UpdatedAt: time.Now().Unix(),
		Deleted:   0,
	},
	{
		ID:        104,
		Name:      "员工录入",
		Path:      "/registration/farminfo/userreg",
		Level:     3,
		Hash:      "registration",
		Redirect:  "",
		Component: "/pages/regs/user",
		IsSub:     false,
		HasSub:    false,
		Single:    false,
		ParentId:  10,
		TenantId:  DefaultTenant,
		CreatedAt: time.Now().Unix(),
		UpdatedAt: time.Now().Unix(),
		Deleted:   0,
	},

	// 个体识别
	{
		ID:        111,
		Name:      "个体识别Item",
		Path:      "/registration/cattle",
		Level:     3,
		Hash:      "registration",
		Redirect:  "",
		Component: "/pages/cattle/cattle",
		IsSub:     true,
		HasSub:    false,
		Single:    true,
		ParentId:  11,
		TenantId:  DefaultTenant,
		CreatedAt: time.Now().Unix(),
		UpdatedAt: time.Now().Unix(),
		Deleted:   0,
	},

	// 生产效率子菜单
	{
		ID:        121,
		Name:      "体尺体重",
		Path:      "/registration/growspanel/growsrecords",
		Level:     3,
		Hash:      "registration",
		Redirect:  "",
		Component: "/pages/cattle/growsrecords",
		IsSub:     true,
		HasSub:    false,
		Single:    false,
		ParentId:  12,
		TenantId:  DefaultTenant,
		CreatedAt: time.Now().Unix(),
		UpdatedAt: time.Now().Unix(),
		Deleted:   0,
	},
	{
		ID:        122,
		Name:      "体况评分",
		Path:      "/registration/growspanel/growsrate",
		Level:     3,
		Hash:      "registration",
		Redirect:  "",
		Component: "/pages/cattle/growsrates",
		IsSub:     true,
		HasSub:    false,
		Single:    false,
		ParentId:  12,
		TenantId:  DefaultTenant,
		CreatedAt: time.Now().Unix(),
		UpdatedAt: time.Now().Unix(),
		Deleted:   0,
	},
	{
		ID:        123,
		Name:      "牛只生长效率",
		Path:      "/registration/growspanel/grows",
		Level:     3,
		Hash:      "registration",
		Redirect:  "",
		Component: "/pages/cattle/grows",
		IsSub:     true,
		HasSub:    false,
		Single:    false,
		ParentId:  12,
		TenantId:  DefaultTenant,
		CreatedAt: time.Now().Unix(),
		UpdatedAt: time.Now().Unix(),
		Deleted:   0,
	},

	// 繁殖状况子菜单
	{
		ID:        131,
		Name:      "产犊登记",
		Path:      "/registration/reproductions/calving",
		Level:     3,
		Hash:      "registration",
		Redirect:  "",
		Component: "/pages/cattle/calving",
		IsSub:     true,
		HasSub:    false,
		Single:    false,
		ParentId:  13,
		TenantId:  DefaultTenant,
		CreatedAt: time.Now().Unix(),
		UpdatedAt: time.Now().Unix(),
		Deleted:   0,
	},
	{
		ID:        132,
		Name:      "发情登记",
		Path:      "/registration/reproductions/estrus",
		Level:     3,
		Hash:      "registration",
		Redirect:  "",
		Component: "/pages/cattle/estrus",
		IsSub:     true,
		HasSub:    false,
		Single:    false,
		ParentId:  13,
		TenantId:  DefaultTenant,
		CreatedAt: time.Now().Unix(),
		UpdatedAt: time.Now().Unix(),
		Deleted:   0,
	},
	{
		ID:        133,
		Name:      "配种登记",
		Path:      "/registration/reproductions/breeding",
		Level:     3,
		Hash:      "registration",
		Redirect:  "",
		Component: "/pages/cattle/breeding",
		IsSub:     true,
		HasSub:    false,
		Single:    false,
		ParentId:  13,
		TenantId:  DefaultTenant,
		CreatedAt: time.Now().Unix(),
		UpdatedAt: time.Now().Unix(),
		Deleted:   0,
	},
	{
		ID:        134,
		Name:      "妊检登记",
		Path:      "/registration/reproductions/pregnancytests",
		Level:     3,
		Hash:      "registration",
		Redirect:  "",
		Component: "/pages/cattle/pregnancytest",
		IsSub:     true,
		HasSub:    false,
		Single:    false,
		ParentId:  13,
		TenantId:  DefaultTenant,
		CreatedAt: time.Now().Unix(),
		UpdatedAt: time.Now().Unix(),
		Deleted:   0,
	},
	{
		ID:        135,
		Name:      "流产登记",
		Path:      "/registration/reproductions/abortions",
		Level:     3,
		Hash:      "registration",
		Redirect:  "",
		Component: "/pages/cattle/abortion",
		IsSub:     true,
		HasSub:    false,
		Single:    false,
		ParentId:  13,
		TenantId:  DefaultTenant,
		CreatedAt: time.Now().Unix(),
		UpdatedAt: time.Now().Unix(),
		Deleted:   0,
	},

	// 疫病防控子菜单
	{
		ID:        141,
		Name:      "疫病信息",
		Path:      "/registration/epidemicspannel/epidemics",
		Level:     3,
		Hash:      "registration",
		Redirect:  "",
		Component: "/pages/epidemics/epidemics",
		IsSub:     true,
		HasSub:    false,
		Single:    false,
		ParentId:  14,
		TenantId:  DefaultTenant,
		CreatedAt: time.Now().Unix(),
		UpdatedAt: time.Now().Unix(),
		Deleted:   0,
	},
	{
		ID:        142,
		Name:      "检疫信息",
		Path:      "/registration/epidemicspannel/inspections",
		Level:     3,
		Hash:      "registration",
		Redirect:  "",
		Component: "/pages/epidemics/inspections",
		IsSub:     true,
		HasSub:    false,
		Single:    false,
		ParentId:  14,
		TenantId:  DefaultTenant,
		CreatedAt: time.Now().Unix(),
		UpdatedAt: time.Now().Unix(),
		Deleted:   0,
	},
	{
		ID:        143,
		Name:      "免疫信息",
		Path:      "/registration/epidemicspannel/immuities",
		Level:     3,
		Hash:      "registration",
		Redirect:  "",
		Component: "/pages/epidemics/immuities",
		IsSub:     true,
		HasSub:    false,
		Single:    false,
		ParentId:  14,
		TenantId:  DefaultTenant,
		CreatedAt: time.Now().Unix(),
		UpdatedAt: time.Now().Unix(),
		Deleted:   0,
	},
	{
		ID:        144,
		Name:      "牛体保健",
		Path:      "/registration/epidemicspannel/healthcare",
		Level:     3,
		Hash:      "registration",
		Redirect:  "",
		Component: "/pages/epidemics/healthcare",
		IsSub:     true,
		HasSub:    false,
		Single:    false,
		ParentId:  14,
		TenantId:  DefaultTenant,
		CreatedAt: time.Now().Unix(),
		UpdatedAt: time.Now().Unix(),
		Deleted:   0,
	},
	{
		ID:        145,
		Name:      "圈舍清毒",
		Path:      "/registration/epidemicspannel/disinfects",
		Level:     3,
		Hash:      "registration",
		Redirect:  "",
		Component: "/pages/epidemics/disinfects",
		IsSub:     true,
		HasSub:    false,
		Single:    false,
		ParentId:  14,
		TenantId:  DefaultTenant,
		CreatedAt: time.Now().Unix(),
		UpdatedAt: time.Now().Unix(),
		Deleted:   0,
	},

	// 物料管理子菜单
	{
		ID:        151,
		Name:      "入库管理",
		Path:      "/registration/materials/materialsadd",
		Level:     3,
		Hash:      "registration",
		Redirect:  "",
		Component: "/pages/materials/add",
		IsSub:     true,
		HasSub:    false,
		Single:    false,
		ParentId:  15,
		TenantId:  DefaultTenant,
		CreatedAt: time.Now().Unix(),
		UpdatedAt: time.Now().Unix(),
		Deleted:   0,
	},
	{
		ID:        152,
		Name:      "入库检测",
		Path:      "/registration/materials/materialscheck",
		Level:     3,
		Hash:      "registration",
		Redirect:  "",
		Component: "/pages/materials/check",
		IsSub:     true,
		HasSub:    false,
		Single:    false,
		ParentId:  15,
		TenantId:  DefaultTenant,
		CreatedAt: time.Now().Unix(),
		UpdatedAt: time.Now().Unix(),
		Deleted:   0,
	},
	{
		ID:        153,
		Name:      "出库管理",
		Path:      "/registration/materials/materialsmgr",
		Level:     3,
		Hash:      "registration",
		Redirect:  "",
		Component: "/pages/materials/mgr",
		IsSub:     true,
		HasSub:    false,
		Single:    false,
		ParentId:  15,
		TenantId:  DefaultTenant,
		CreatedAt: time.Now().Unix(),
		UpdatedAt: time.Now().Unix(),
		Deleted:   0,
	},
	{
		ID:        154,
		Name:      "库存流水",
		Path:      "/registration/materials/materialsflows",
		Level:     3,
		Hash:      "registration",
		Redirect:  "",
		Component: "/pages/materials/flows",
		IsSub:     true,
		HasSub:    false,
		Single:    false,
		ParentId:  15,
		TenantId:  DefaultTenant,
		CreatedAt: time.Now().Unix(),
		UpdatedAt: time.Now().Unix(),
		Deleted:   0,
	},

	// 饲喂管理子菜单
	{
		ID:        161,
		Name:      "精料配方",
		Path:      "/registration/feedingmgr/concentrate",
		Level:     3,
		Hash:      "registration",
		Redirect:  "",
		Component: "/pages/feedingmgr/concentrate",
		IsSub:     true,
		HasSub:    false,
		Single:    false,
		ParentId:  16,
		TenantId:  DefaultTenant,
		CreatedAt: time.Now().Unix(),
		UpdatedAt: time.Now().Unix(),
		Deleted:   0,
	},
	{
		ID:        162,
		Name:      "精料加工",
		Path:      "/registration/feedingmgr/concentrateprocess",
		Level:     3,
		Hash:      "registration",
		Redirect:  "",
		Component: "/pages/feedingmgr/concentrateprocess",
		IsSub:     true,
		HasSub:    false,
		Single:    false,
		ParentId:  16,
		TenantId:  DefaultTenant,
		CreatedAt: time.Now().Unix(),
		UpdatedAt: time.Now().Unix(),
		Deleted:   0,
	},
	{
		ID:        163,
		Name:      "日粮配方",
		Path:      "/registration/feedingmgr/rations",
		Level:     3,
		Hash:      "registration",
		Redirect:  "",
		Component: "/pages/feedingmgr/ration",
		IsSub:     true,
		HasSub:    false,
		Single:    false,
		ParentId:  16,
		TenantId:  DefaultTenant,
		CreatedAt: time.Now().Unix(),
		UpdatedAt: time.Now().Unix(),
		Deleted:   0,
	},
	{
		ID:        164,
		Name:      "饲喂记录",
		Path:      "/registration/feedingmgr/feedrecords",
		Level:     3,
		Hash:      "registration",
		Redirect:  "",
		Component: "/pages/feedingmgr/feedrecord",
		IsSub:     true,
		HasSub:    false,
		Single:    false,
		ParentId:  16,
		TenantId:  DefaultTenant,
		CreatedAt: time.Now().Unix(),
		UpdatedAt: time.Now().Unix(),
		Deleted:   0,
	},

	// 牛群异动子菜单
	{
		ID:        171,
		Name:      "牛只入栏",
		Path:      "/registration/cattlegroups/cattlein",
		Level:     3,
		Hash:      "registration",
		Redirect:  "",
		Component: "/pages/cattlegroups/in",
		IsSub:     true,
		HasSub:    false,
		Single:    false,
		ParentId:  17,
		TenantId:  DefaultTenant,
		CreatedAt: time.Now().Unix(),
		UpdatedAt: time.Now().Unix(),
		Deleted:   0,
	},
	{
		ID:        172,
		Name:      "牛只出栏",
		Path:      "/registration/cattlegroups/cattleout",
		Level:     3,
		Hash:      "registration",
		Redirect:  "",
		Component: "/pages/cattlegroups/out",
		IsSub:     true,
		HasSub:    false,
		Single:    false,
		ParentId:  17,
		TenantId:  DefaultTenant,
		CreatedAt: time.Now().Unix(),
		UpdatedAt: time.Now().Unix(),
		Deleted:   0,
	},
	{
		ID:        173,
		Name:      "饲喂分群",
		Path:      "/registration/cattlegroups/cattlein",
		Level:     3,
		Hash:      "registration",
		Redirect:  "",
		Component: "/pages/cattlegroups/in",
		IsSub:     true,
		HasSub:    false,
		Single:    false,
		ParentId:  17,
		TenantId:  DefaultTenant,
		CreatedAt: time.Now().Unix(),
		UpdatedAt: time.Now().Unix(),
		Deleted:   0,
	},
	{
		ID:        174,
		Name:      "转舍登记",
		Path:      "/registration/cattlegroups/cattlein",
		Level:     3,
		Hash:      "registration",
		Redirect:  "",
		Component: "/pages/cattlegroups/in",
		IsSub:     true,
		HasSub:    false,
		Single:    false,
		ParentId:  17,
		TenantId:  DefaultTenant,
		CreatedAt: time.Now().Unix(),
		UpdatedAt: time.Now().Unix(),
		Deleted:   0,
	},
	{
		ID:        175,
		Name:      "死亡登记",
		Path:      "/registration/cattlegroups/cattlein",
		Level:     3,
		Hash:      "registration",
		Redirect:  "",
		Component: "/pages/cattlegroups/in",
		IsSub:     true,
		HasSub:    false,
		Single:    false,
		ParentId:  17,
		TenantId:  DefaultTenant,
		CreatedAt: time.Now().Unix(),
		UpdatedAt: time.Now().Unix(),
		Deleted:   0,
	},
}
