package db

import (
	"cattleai/ent"
	"time"
)

const DefaultTenant = "system_tenant"

var apis = []ent.API{
	{
		ID:        1,
		Name:      "首页",
		Path:      "/",
		Level:     1,
		Hash:      "index",
		Redirect:  "/index",
		Component: "/layouts/main",
		IsSub:     false,
		HasSub:    false,
		Single:    false,
		ParentId:  -1,
		TenantId:  DefaultTenant,
		CreatedAt: time.Now().Unix(),
		UpdatedAt: time.Now().Unix(),
		Deleted:   0,
	},
	{
		ID:        2,
		Name:      "信息登记",
		Path:      "/registration",
		Level:     1,
		Hash:      "registration",
		Redirect:  "/registration/farminfo/farmreg",
		Component: "/layouts/main",
		IsSub:     false,
		HasSub:    true,
		Single:    false,
		ParentId:  -1,
		TenantId:  DefaultTenant,
		CreatedAt: time.Now().Unix(),
		UpdatedAt: time.Now().Unix(),
		Deleted:   0,
	},
	{
		ID:        3,
		Name:      "信息查询",
		Path:      "/informations",
		Level:     1,
		Hash:      "informations",
		Redirect:  "/informations/farminfo/farmreg",
		Component: "/layouts/main",
		IsSub:     false,
		HasSub:    true,
		Single:    false,
		ParentId:  -1,
		TenantId:  DefaultTenant,
		CreatedAt: time.Now().Unix(),
		UpdatedAt: time.Now().Unix(),
		Deleted:   0,
	},
	{
		ID:        4,
		Name:      "生产管理",
		Path:      "/pm",
		Level:     1,
		Hash:      "pm",
		Redirect:  "/pm/farminfo/farmreg",
		Component: "/layouts/main",
		IsSub:     false,
		HasSub:    true,
		Single:    false,
		ParentId:  -1,
		TenantId:  DefaultTenant,
		CreatedAt: time.Now().Unix(),
		UpdatedAt: time.Now().Unix(),
		Deleted:   0,
	},
	{
		ID:        5,
		Name:      "屠宰分割",
		Path:      "/slaughter",
		Level:     1,
		Hash:      "slaughter",
		Redirect:  "/slaughter/farminfo/farmreg",
		Component: "/layouts/main",
		IsSub:     false,
		HasSub:    true,
		Single:    false,
		ParentId:  -1,
		TenantId:  DefaultTenant,
		CreatedAt: time.Now().Unix(),
		UpdatedAt: time.Now().Unix(),
		Deleted:   0,
	},
	{
		ID:        6,
		Name:      "财务管理",
		Path:      "/financial",
		Level:     1,
		Hash:      "financial",
		Redirect:  "/financial/farminfo/farmreg",
		Component: "/layouts/main",
		IsSub:     false,
		HasSub:    true,
		Single:    false,
		ParentId:  -1,
		TenantId:  DefaultTenant,
		CreatedAt: time.Now().Unix(),
		UpdatedAt: time.Now().Unix(),
		Deleted:   0,
	},
	{
		ID:        7,
		Name:      "信息统计",
		Path:      "/statistics",
		Level:     1,
		Hash:      "statistics",
		Redirect:  "/statistics/farminfo/farmreg",
		Component: "/layouts/main",
		IsSub:     false,
		HasSub:    true,
		Single:    false,
		ParentId:  -1,
		TenantId:  DefaultTenant,
		CreatedAt: time.Now().Unix(),
		UpdatedAt: time.Now().Unix(),
		Deleted:   0,
	},
	{
		ID:        8,
		Name:      "分析报表",
		Path:      "/analysis",
		Level:     1,
		Hash:      "analysis",
		Redirect:  "/analysis/farminfo/farmreg",
		Component: "/layouts/main",
		IsSub:     false,
		HasSub:    true,
		Single:    false,
		ParentId:  -1,
		TenantId:  DefaultTenant,
		CreatedAt: time.Now().Unix(),
		UpdatedAt: time.Now().Unix(),
		Deleted:   0,
	},
	{
		ID:        9,
		Name:      "基础资料",
		Path:      "/basics",
		Level:     1,
		Hash:      "basics",
		Redirect:  "/basics/farminfo/farmreg",
		Component: "/layouts/main",
		IsSub:     false,
		HasSub:    true,
		Single:    false,
		ParentId:  -1,
		TenantId:  DefaultTenant,
		CreatedAt: time.Now().Unix(),
		UpdatedAt: time.Now().Unix(),
		Deleted:   0,
	},
	{
		ID:        91,
		Name:      "系统设置",
		Path:      "/settings",
		Level:     1,
		Hash:      "settings",
		Redirect:  "/settings/tenants",
		Component: "/layouts/main",
		IsSub:     false,
		HasSub:    true,
		Single:    false,
		ParentId:  -1,
		TenantId:  DefaultTenant,
		CreatedAt: time.Now().Unix(),
		UpdatedAt: time.Now().Unix(),
		Deleted:   0,
	},
	{
		ID:        911,
		Name:      "租户设置",
		Path:      "/settings/tenants",
		Level:     2,
		Hash:      "settings",
		Component: "/layouts/sub",
		IsSub:     false,
		HasSub:    false,
		Single:    false,
		ParentId:  91,
		TenantId:  DefaultTenant,
		CreatedAt: time.Now().Unix(),
		UpdatedAt: time.Now().Unix(),
		Deleted:   0,
	},
	// 信息登记子菜单
	{
		ID:        10,
		Name:      "牛场信息",
		Path:      "/registration/farminfo",
		Level:     2,
		Hash:      "registration",
		Redirect:  "",
		Component: "/layouts/sub",
		IsSub:     true,
		HasSub:    false,
		Single:    false,
		ParentId:  2,
		TenantId:  DefaultTenant,
		CreatedAt: time.Now().Unix(),
		UpdatedAt: time.Now().Unix(),
		Deleted:   0,
	},
	{
		ID:        11,
		Name:      "个体识别",
		Path:      "/registration/cattle",
		Level:     2,
		Hash:      "registration",
		Redirect:  "",
		Component: "/layouts/sub",
		IsSub:     true,
		HasSub:    false,
		Single:    true,
		ParentId:  2,
		TenantId:  DefaultTenant,
		CreatedAt: time.Now().Unix(),
		UpdatedAt: time.Now().Unix(),
		Deleted:   0,
	},
	{
		ID:        12,
		Name:      "生长效率",
		Path:      "/registration/growspanel",
		Level:     2,
		Hash:      "registration",
		Redirect:  "",
		Component: "/layouts/sub",
		IsSub:     true,
		HasSub:    false,
		Single:    false,
		ParentId:  2,
		TenantId:  DefaultTenant,
		CreatedAt: time.Now().Unix(),
		UpdatedAt: time.Now().Unix(),
		Deleted:   0,
	},
	{
		ID:        13,
		Name:      "繁殖状况",
		Path:      "/registration/reproductions",
		Level:     2,
		Hash:      "registration",
		Redirect:  "",
		Component: "/layouts/sub",
		IsSub:     true,
		HasSub:    false,
		Single:    false,
		ParentId:  2,
		TenantId:  DefaultTenant,
		CreatedAt: time.Now().Unix(),
		UpdatedAt: time.Now().Unix(),
		Deleted:   0,
	},
	{
		ID:        14,
		Name:      "疫病防控",
		Path:      "/registration/epidemicspannel",
		Level:     2,
		Hash:      "registration",
		Redirect:  "",
		Component: "/layouts/sub",
		IsSub:     true,
		HasSub:    false,
		Single:    false,
		ParentId:  2,
		TenantId:  DefaultTenant,
		CreatedAt: time.Now().Unix(),
		UpdatedAt: time.Now().Unix(),
		Deleted:   0,
	},
	{
		ID:        15,
		Name:      "物料管理",
		Path:      "/registration/materials",
		Level:     2,
		Hash:      "registration",
		Redirect:  "",
		Component: "/layouts/sub",
		IsSub:     true,
		HasSub:    false,
		Single:    false,
		ParentId:  2,
		TenantId:  DefaultTenant,
		CreatedAt: time.Now().Unix(),
		UpdatedAt: time.Now().Unix(),
		Deleted:   0,
	},
	{
		ID:        16,
		Name:      "饲喂管理",
		Path:      "/registration/feedingmgr",
		Level:     2,
		Hash:      "registration",
		Redirect:  "",
		Component: "/layouts/sub",
		IsSub:     true,
		HasSub:    false,
		Single:    false,
		ParentId:  2,
		TenantId:  DefaultTenant,
		CreatedAt: time.Now().Unix(),
		UpdatedAt: time.Now().Unix(),
		Deleted:   0,
	},
	{
		ID:        17,
		Name:      "牛群异动",
		Path:      "/registration/cattlegroups",
		Level:     2,
		Hash:      "registration",
		Redirect:  "",
		Component: "/layouts/sub",
		IsSub:     true,
		HasSub:    false,
		Single:    false,
		ParentId:  2,
		TenantId:  DefaultTenant,
		CreatedAt: time.Now().Unix(),
		UpdatedAt: time.Now().Unix(),
		Deleted:   0,
	},
	{
		ID:        18,
		Name:      "屠宰分割",
		Path:      "/registration/slaughter",
		Level:     2,
		Hash:      "registration",
		Redirect:  "",
		Component: "/layouts/sub",
		IsSub:     true,
		HasSub:    false,
		Single:    false,
		ParentId:  2,
		TenantId:  DefaultTenant,
		CreatedAt: time.Now().Unix(),
		UpdatedAt: time.Now().Unix(),
		Deleted:   0,
	},
	{
		ID:        19,
		Name:      "批量导入",
		Path:      "/registration/batchimport",
		Level:     2,
		Hash:      "registration",
		Redirect:  "",
		Component: "/layouts/sub",
		IsSub:     true,
		HasSub:    false,
		Single:    true,
		ParentId:  2,
		TenantId:  DefaultTenant,
		CreatedAt: time.Now().Unix(),
		UpdatedAt: time.Now().Unix(),
		Deleted:   0,
	},

	// 牛场信息子菜单
	{
		ID:        101,
		Name:      "牛场录入",
		Path:      "/registration/farminfo/farmreg",
		Level:     3,
		Hash:      "registration",
		Redirect:  "",
		Component: "/pages/regs/farmreg",
		IsSub:     false,
		HasSub:    false,
		Single:    false,
		ParentId:  10,
		TenantId:  DefaultTenant,
		CreatedAt: time.Now().Unix(),
		UpdatedAt: time.Now().Unix(),
		Deleted:   0,
	},
	{
		ID:        102,
		Name:      "牛舍录入",
		Path:      "/registration/farminfo/cattleshedreg",
		Level:     3,
		Hash:      "registration",
		Redirect:  "",
		Component: "/pages/regs/cattleshedreg",
		IsSub:     false,
		HasSub:    false,
		Single:    false,
		ParentId:  10,
		TenantId:  DefaultTenant,
		CreatedAt: time.Now().Unix(),
		UpdatedAt: time.Now().Unix(),
		Deleted:   0,
	},
	{
		ID:        103,
		Name:      "生产环境",
		Path:      "/registration/farminfo/surroundingreg",
		Level:     3,
		Hash:      "registration",
		Redirect:  "",
		Component: "/pages/regs/surrounding",
		IsSub:     false,
		HasSub:    false,
		Single:    false,
		ParentId:  10,
		TenantId:  DefaultTenant,
		CreatedAt: time.Now().Unix(),
		UpdatedAt: time.Now().Unix(),
		Deleted:   0,
	},
	{
		ID:        104,
		Name:      "员工录入",
		Path:      "/registration/farminfo/userreg",
		Level:     3,
		Hash:      "registration",
		Redirect:  "",
		Component: "/pages/regs/user",
		IsSub:     false,
		HasSub:    false,
		Single:    false,
		ParentId:  10,
		TenantId:  DefaultTenant,
		CreatedAt: time.Now().Unix(),
		UpdatedAt: time.Now().Unix(),
		Deleted:   0,
	},
}
