package db

import (
	"cattleai/ent"
	"time"
)

const DefaultTenant = "system_tenant"

var apis = []ent.API{
	{
		ID:        1,
		Name:      "首页",
		Path:      "/",
		Level:     1,
		Hash:      "index",
		Redirect:  "/index",
		Component: "/layouts/main",
		IsSub:     false,
		HasSub:    false,
		Single:    false,
		ParentId:  -1,
		TenantId:  DefaultTenant,
		CreatedAt: time.Now().Unix(),
		UpdatedAt: time.Now().Unix(),
		Deleted:   0,
	},
	{
		ID:        2,
		Name:      "信息登记",
		Path:      "/registration",
		Level:     1,
		Hash:      "registration",
		Redirect:  "/registration/farminfo/farmreg",
		Component: "/layouts/main",
		IsSub:     false,
		HasSub:    true,
		Single:    false,
		ParentId:  -1,
		TenantId:  DefaultTenant,
		CreatedAt: time.Now().Unix(),
		UpdatedAt: time.Now().Unix(),
		Deleted:   0,
	},
	{
		ID:        3,
		Name:      "信息查询",
		Path:      "/informations",
		Level:     1,
		Hash:      "informations",
		Redirect:  "/informations/farminfo/farmreg",
		Component: "/layouts/main",
		IsSub:     false,
		HasSub:    true,
		Single:    false,
		ParentId:  -1,
		TenantId:  DefaultTenant,
		CreatedAt: time.Now().Unix(),
		UpdatedAt: time.Now().Unix(),
		Deleted:   0,
	},
	{
		ID:        4,
		Name:      "生产管理",
		Path:      "/pm",
		Level:     1,
		Hash:      "pm",
		Redirect:  "/pm/farminfo/farmreg",
		Component: "/layouts/main",
		IsSub:     false,
		HasSub:    true,
		Single:    false,
		ParentId:  -1,
		TenantId:  DefaultTenant,
		CreatedAt: time.Now().Unix(),
		UpdatedAt: time.Now().Unix(),
		Deleted:   0,
	},
	{
		ID:        5,
		Name:      "屠宰分割",
		Path:      "/slaughter",
		Level:     1,
		Hash:      "slaughter",
		Redirect:  "/slaughter/farminfo/farmreg",
		Component: "/layouts/main",
		IsSub:     false,
		HasSub:    true,
		Single:    false,
		ParentId:  -1,
		TenantId:  DefaultTenant,
		CreatedAt: time.Now().Unix(),
		UpdatedAt: time.Now().Unix(),
		Deleted:   0,
	},
	{
		ID:        6,
		Name:      "财务管理",
		Path:      "/financial",
		Level:     1,
		Hash:      "financial",
		Redirect:  "/financial/farminfo/farmreg",
		Component: "/layouts/main",
		IsSub:     false,
		HasSub:    true,
		Single:    false,
		ParentId:  -1,
		TenantId:  DefaultTenant,
		CreatedAt: time.Now().Unix(),
		UpdatedAt: time.Now().Unix(),
		Deleted:   0,
	},
	{
		ID:        7,
		Name:      "信息统计",
		Path:      "/statistics",
		Level:     1,
		Hash:      "statistics",
		Redirect:  "/statistics/farminfo/farmreg",
		Component: "/layouts/main",
		IsSub:     false,
		HasSub:    true,
		Single:    false,
		ParentId:  -1,
		TenantId:  DefaultTenant,
		CreatedAt: time.Now().Unix(),
		UpdatedAt: time.Now().Unix(),
		Deleted:   0,
	},

	// 信息统计
	{
		ID:        711,
		Name:      "运营看板",
		Path:      "/statistics/dashboard",
		Level:     2,
		Hash:      "statistics",
		Redirect:  "",
		Component: "/pages/materials/list",
		IsSub:     true,
		HasSub:    false,
		Single:    true,
		ParentId:  7,
		TenantId:  DefaultTenant,
		CreatedAt: time.Now().Unix(),
		UpdatedAt: time.Now().Unix(),
		Deleted:   0,
	},
	{
		ID:        712,
		Name:      "牛群统计",
		Path:      "/statistics/groups",
		Level:     2,
		Hash:      "statistics",
		Redirect:  "",
		Component: "/pages/materials/list",
		IsSub:     true,
		HasSub:    false,
		Single:    true,
		ParentId:  7,
		TenantId:  DefaultTenant,
		CreatedAt: time.Now().Unix(),
		UpdatedAt: time.Now().Unix(),
		Deleted:   0,
	},
	{
		ID:        713,
		Name:      "饲喂统计",
		Path:      "/statistics/feeds",
		Level:     2,
		Hash:      "statistics",
		Redirect:  "",
		Component: "/pages/materials/list",
		IsSub:     true,
		HasSub:    false,
		Single:    true,
		ParentId:  7,
		TenantId:  DefaultTenant,
		CreatedAt: time.Now().Unix(),
		UpdatedAt: time.Now().Unix(),
		Deleted:   0,
	},
	{
		ID:        714,
		Name:      "繁育统计",
		Path:      "/statistics/breeds",
		Level:     2,
		Hash:      "statistics",
		Redirect:  "",
		Component: "/pages/materials/list",
		IsSub:     true,
		HasSub:    false,
		Single:    true,
		ParentId:  7,
		TenantId:  DefaultTenant,
		CreatedAt: time.Now().Unix(),
		UpdatedAt: time.Now().Unix(),
		Deleted:   0,
	},
	{
		ID:        715,
		Name:      "兽医统计",
		Path:      "/statistics/doctors",
		Level:     2,
		Hash:      "statistics",
		Redirect:  "",
		Component: "/pages/materials/list",
		IsSub:     true,
		HasSub:    false,
		Single:    true,
		ParentId:  7,
		TenantId:  DefaultTenant,
		CreatedAt: time.Now().Unix(),
		UpdatedAt: time.Now().Unix(),
		Deleted:   0,
	},
	{
		ID:        716,
		Name:      "财务统计",
		Path:      "/statistics/financials",
		Level:     2,
		Hash:      "statistics",
		Redirect:  "",
		Component: "/pages/materials/list",
		IsSub:     true,
		HasSub:    false,
		Single:    true,
		ParentId:  7,
		TenantId:  DefaultTenant,
		CreatedAt: time.Now().Unix(),
		UpdatedAt: time.Now().Unix(),
		Deleted:   0,
	},
	// end

	//
	{
		ID:        8,
		Name:      "分析报表",
		Path:      "/analysis",
		Level:     1,
		Hash:      "analysis",
		Redirect:  "/analysis/farminfo/farmreg",
		Component: "/layouts/main",
		IsSub:     false,
		HasSub:    true,
		Single:    false,
		ParentId:  -1,
		TenantId:  DefaultTenant,
		CreatedAt: time.Now().Unix(),
		UpdatedAt: time.Now().Unix(),
		Deleted:   0,
	},
	{
		ID:        9,
		Name:      "基础资料",
		Path:      "/basics",
		Level:     1,
		Hash:      "basics",
		Redirect:  "/basics/farminfo/farmreg",
		Component: "/layouts/main",
		IsSub:     false,
		HasSub:    true,
		Single:    false,
		ParentId:  -1,
		TenantId:  DefaultTenant,
		CreatedAt: time.Now().Unix(),
		UpdatedAt: time.Now().Unix(),
		Deleted:   0,
	},
	{
		ID:        91,
		Name:      "系统设置",
		Path:      "/settings",
		Level:     1,
		Hash:      "settings",
		Redirect:  "/settings/tenants",
		Component: "/layouts/main",
		IsSub:     false,
		HasSub:    true,
		Single:    false,
		ParentId:  -1,
		TenantId:  DefaultTenant,
		CreatedAt: time.Now().Unix(),
		UpdatedAt: time.Now().Unix(),
		Deleted:   0,
	},
	{
		ID:        911,
		Name:      "租户设置",
		Path:      "/settings/tenants",
		Level:     2,
		Hash:      "settings",
		Component: "/layouts/sub",
		IsSub:     false,
		HasSub:    false,
		Single:    false,
		ParentId:  91,
		TenantId:  DefaultTenant,
		CreatedAt: time.Now().Unix(),
		UpdatedAt: time.Now().Unix(),
		Deleted:   0,
	},

	// 信息登记子菜单
	{
		ID:        10,
		Name:      "牛场信息",
		Path:      "/registration/farminfo",
		Level:     2,
		Hash:      "registration",
		Redirect:  "",
		Component: "/layouts/sub",
		IsSub:     true,
		HasSub:    false,
		Single:    false,
		ParentId:  2,
		TenantId:  DefaultTenant,
		CreatedAt: time.Now().Unix(),
		UpdatedAt: time.Now().Unix(),
		Deleted:   0,
	},
	{
		ID:        11,
		Name:      "个体识别",
		Path:      "/registration/cattle",
		Level:     2,
		Hash:      "registration",
		Redirect:  "",
		Component: "/layouts/sub",
		IsSub:     true,
		HasSub:    false,
		Single:    true,
		ParentId:  2,
		TenantId:  DefaultTenant,
		CreatedAt: time.Now().Unix(),
		UpdatedAt: time.Now().Unix(),
		Deleted:   0,
	},
	{
		ID:        15,
		Name:      "物料管理",
		Path:      "/registration/materials",
		Level:     2,
		Hash:      "registration",
		Redirect:  "",
		Component: "/layouts/sub",
		IsSub:     true,
		HasSub:    false,
		Single:    false,
		ParentId:  2,
		TenantId:  DefaultTenant,
		CreatedAt: time.Now().Unix(),
		UpdatedAt: time.Now().Unix(),
		Deleted:   0,
	},
	{
		ID:        16,
		Name:      "饲喂管理",
		Path:      "/registration/feedingmgr",
		Level:     2,
		Hash:      "registration",
		Redirect:  "",
		Component: "/layouts/sub",
		IsSub:     true,
		HasSub:    false,
		Single:    false,
		ParentId:  2,
		TenantId:  DefaultTenant,
		CreatedAt: time.Now().Unix(),
		UpdatedAt: time.Now().Unix(),
		Deleted:   0,
	},
	{
		ID:        18,
		Name:      "屠宰分割",
		Path:      "/registration/slaughter",
		Level:     2,
		Hash:      "registration",
		Redirect:  "",
		Component: "/layouts/sub",
		IsSub:     true,
		HasSub:    false,
		Single:    false,
		ParentId:  2,
		TenantId:  DefaultTenant,
		CreatedAt: time.Now().Unix(),
		UpdatedAt: time.Now().Unix(),
		Deleted:   0,
	},
	{
		ID:        19,
		Name:      "批量导入",
		Path:      "/registration/batchimport",
		Level:     2,
		Hash:      "registration",
		Redirect:  "",
		Component: "/layouts/sub",
		IsSub:     true,
		HasSub:    false,
		Single:    true,
		ParentId:  2,
		TenantId:  DefaultTenant,
		CreatedAt: time.Now().Unix(),
		UpdatedAt: time.Now().Unix(),
		Deleted:   0,
	},

	// 牛场信息子菜单
	{
		ID:        101,
		Name:      "牛场录入",
		Path:      "/registration/farminfo/farmreg",
		Level:     3,
		Hash:      "registration",
		Redirect:  "",
		Component: "/pages/regs/farmreg",
		IsSub:     false,
		HasSub:    false,
		Single:    false,
		ParentId:  10,
		TenantId:  DefaultTenant,
		CreatedAt: time.Now().Unix(),
		UpdatedAt: time.Now().Unix(),
		Deleted:   0,
	},
	{
		ID:        102,
		Name:      "牛舍录入",
		Path:      "/registration/farminfo/cattleshedreg",
		Level:     3,
		Hash:      "registration",
		Redirect:  "",
		Component: "/pages/regs/cattleshedreg",
		IsSub:     false,
		HasSub:    false,
		Single:    false,
		ParentId:  10,
		TenantId:  DefaultTenant,
		CreatedAt: time.Now().Unix(),
		UpdatedAt: time.Now().Unix(),
		Deleted:   0,
	},
	{
		ID:        103,
		Name:      "生产环境",
		Path:      "/registration/farminfo/surroundingreg",
		Level:     3,
		Hash:      "registration",
		Redirect:  "",
		Component: "/pages/regs/surrounding",
		IsSub:     false,
		HasSub:    false,
		Single:    false,
		ParentId:  10,
		TenantId:  DefaultTenant,
		CreatedAt: time.Now().Unix(),
		UpdatedAt: time.Now().Unix(),
		Deleted:   0,
	},
	{
		ID:        104,
		Name:      "员工录入",
		Path:      "/registration/farminfo/userreg",
		Level:     3,
		Hash:      "registration",
		Redirect:  "",
		Component: "/pages/regs/user",
		IsSub:     false,
		HasSub:    false,
		Single:    false,
		ParentId:  10,
		TenantId:  DefaultTenant,
		CreatedAt: time.Now().Unix(),
		UpdatedAt: time.Now().Unix(),
		Deleted:   0,
	},

	// 个体识别
	{
		ID:        111,
		Name:      "个体识别Item",
		Path:      "/registration/cattle",
		Level:     3,
		Hash:      "registration",
		Redirect:  "",
		Component: "/pages/cattle/cattle",
		IsSub:     true,
		HasSub:    false,
		Single:    true,
		ParentId:  11,
		TenantId:  DefaultTenant,
		CreatedAt: time.Now().Unix(),
		UpdatedAt: time.Now().Unix(),
		Deleted:   0,
	},

	// 物料管理子菜单
	{
		ID:        151,
		Name:      "物料列表",
		Path:      "/registration/materials/materials",
		Level:     3,
		Hash:      "registration",
		Redirect:  "",
		Component: "/pages/materials/list",
		IsSub:     true,
		HasSub:    false,
		Single:    false,
		ParentId:  15,
		TenantId:  DefaultTenant,
		CreatedAt: time.Now().Unix(),
		UpdatedAt: time.Now().Unix(),
		Deleted:   0,
	},
	{
		ID:        152,
		Name:      "出库入库",
		Path:      "/registration/materials/inandout",
		Level:     3,
		Hash:      "registration",
		Redirect:  "",
		Component: "/pages/materials/inandout",
		IsSub:     true,
		HasSub:    false,
		Single:    false,
		ParentId:  15,
		TenantId:  DefaultTenant,
		CreatedAt: time.Now().Unix(),
		UpdatedAt: time.Now().Unix(),
		Deleted:   0,
	},
	{
		ID:        154,
		Name:      "库存流水",
		Path:      "/registration/materials/inventoryflows",
		Level:     3,
		Hash:      "registration",
		Redirect:  "",
		Component: "/pages/materials/inventoryflows",
		IsSub:     true,
		HasSub:    false,
		Single:    false,
		ParentId:  15,
		TenantId:  DefaultTenant,
		CreatedAt: time.Now().Unix(),
		UpdatedAt: time.Now().Unix(),
		Deleted:   0,
	},

	// 饲喂管理子菜单
	{
		ID:        161,
		Name:      "精料配方",
		Path:      "/registration/feedingmgr/concentrate",
		Level:     3,
		Hash:      "registration",
		Redirect:  "",
		Component: "/pages/feedingmgr/concentrate",
		IsSub:     true,
		HasSub:    false,
		Single:    false,
		ParentId:  16,
		TenantId:  DefaultTenant,
		CreatedAt: time.Now().Unix(),
		UpdatedAt: time.Now().Unix(),
		Deleted:   0,
	},
	{
		ID:        162,
		Name:      "精料加工",
		Path:      "/registration/feedingmgr/concentrateprocess",
		Level:     3,
		Hash:      "registration",
		Redirect:  "",
		Component: "/pages/feedingmgr/concentrateprocess",
		IsSub:     true,
		HasSub:    false,
		Single:    false,
		ParentId:  16,
		TenantId:  DefaultTenant,
		CreatedAt: time.Now().Unix(),
		UpdatedAt: time.Now().Unix(),
		Deleted:   0,
	},
	{
		ID:        163,
		Name:      "日粮配方",
		Path:      "/registration/feedingmgr/rations",
		Level:     3,
		Hash:      "registration",
		Redirect:  "",
		Component: "/pages/feedingmgr/ration",
		IsSub:     true,
		HasSub:    false,
		Single:    false,
		ParentId:  16,
		TenantId:  DefaultTenant,
		CreatedAt: time.Now().Unix(),
		UpdatedAt: time.Now().Unix(),
		Deleted:   0,
	},
	{
		ID:        164,
		Name:      "饲喂记录",
		Path:      "/registration/feedingmgr/feedrecords",
		Level:     3,
		Hash:      "registration",
		Redirect:  "",
		Component: "/pages/feedingmgr/feedrecord",
		IsSub:     true,
		HasSub:    false,
		Single:    false,
		ParentId:  16,
		TenantId:  DefaultTenant,
		CreatedAt: time.Now().Unix(),
		UpdatedAt: time.Now().Unix(),
		Deleted:   0,
	},
	// 信息查询子目录
	{
		ID:        301,
		Name:      "个体查询",
		Path:      "/informations/single",
		Level:     2,
		Hash:      "informations",
		Redirect:  "",
		Component: "/layouts/sub",
		IsSub:     true,
		HasSub:    false,
		Single:    true,
		ParentId:  3,
		TenantId:  DefaultTenant,
		CreatedAt: time.Now().Unix(),
		UpdatedAt: time.Now().Unix(),
		Deleted:   0,
	},

	{
		ID:        303,
		Name:      "事件查询",
		Path:      "/informations/events",
		Level:     2,
		Hash:      "informations",
		Redirect:  "",
		Component: "/layouts/sub",
		IsSub:     true,
		HasSub:    false,
		Single:    true,
		ParentId:  3,
		TenantId:  DefaultTenant,
		CreatedAt: time.Now().Unix(),
		UpdatedAt: time.Now().Unix(),
		Deleted:   0,
	},
	{
		ID:        305,
		Name:      "操作日志",
		Path:      "/informations/oplogs",
		Level:     2,
		Hash:      "informations",
		Redirect:  "",
		Component: "/layouts/sub",
		IsSub:     true,
		HasSub:    false,
		Single:    true,
		ParentId:  3,
		TenantId:  DefaultTenant,
		CreatedAt: time.Now().Unix(),
		UpdatedAt: time.Now().Unix(),
		Deleted:   0,
	},

	// 基础资料子目录
	{
		ID:        901,
		Name:      "自定义项",
		Path:      "/basics/custom",
		Level:     2,
		Hash:      "basics",
		Redirect:  "",
		Component: "/layouts/sub",
		IsSub:     true,
		HasSub:    true,
		Single:    false,
		ParentId:  9,
		TenantId:  DefaultTenant,
		CreatedAt: time.Now().Unix(),
		UpdatedAt: time.Now().Unix(),
		Deleted:   0,
	},
	{
		ID:        902,
		Name:      "机构设置",
		Path:      "/basics/organizations",
		Level:     2,
		Hash:      "basics",
		Redirect:  "",
		Component: "/layouts/sub",
		IsSub:     true,
		HasSub:    false,
		Single:    true,
		ParentId:  9,
		TenantId:  DefaultTenant,
		CreatedAt: time.Now().Unix(),
		UpdatedAt: time.Now().Unix(),
		Deleted:   0,
	},
	{
		ID:        903,
		Name:      "人员设置",
		Path:      "/basics/users",
		Level:     2,
		Hash:      "basics",
		Redirect:  "",
		Component: "/layouts/sub",
		IsSub:     true,
		HasSub:    false,
		Single:    true,
		ParentId:  9,
		TenantId:  DefaultTenant,
		CreatedAt: time.Now().Unix(),
		UpdatedAt: time.Now().Unix(),
		Deleted:   0,
	},
	{
		ID:        904,
		Name:      "生产管理",
		Path:      "/basics/pm",
		Level:     2,
		Hash:      "basics",
		Redirect:  "",
		Component: "/layouts/sub",
		IsSub:     true,
		HasSub:    true,
		Single:    false,
		ParentId:  9,
		TenantId:  DefaultTenant,
		CreatedAt: time.Now().Unix(),
		UpdatedAt: time.Now().Unix(),
		Deleted:   0,
	},
	{
		ID:        905,
		Name:      "圈舍设置",
		Path:      "/basics/sheds",
		Level:     2,
		Hash:      "basics",
		Redirect:  "",
		Component: "/layouts/sub",
		IsSub:     true,
		HasSub:    false,
		Single:    true,
		ParentId:  9,
		TenantId:  DefaultTenant,
		CreatedAt: time.Now().Unix(),
		UpdatedAt: time.Now().Unix(),
		Deleted:   0,
	},
	{
		ID:        906,
		Name:      "库房设置",
		Path:      "/basics/storage",
		Level:     2,
		Hash:      "basics",
		Redirect:  "",
		Component: "/layouts/sub",
		IsSub:     true,
		HasSub:    false,
		Single:    true,
		ParentId:  9,
		TenantId:  DefaultTenant,
		CreatedAt: time.Now().Unix(),
		UpdatedAt: time.Now().Unix(),
		Deleted:   0,
	},
	{
		ID:        907,
		Name:      "客户管理",
		Path:      "/basics/ur",
		Level:     2,
		Hash:      "basics",
		Redirect:  "",
		Component: "/layouts/sub",
		IsSub:     true,
		HasSub:    false,
		Single:    true,
		ParentId:  9,
		TenantId:  DefaultTenant,
		CreatedAt: time.Now().Unix(),
		UpdatedAt: time.Now().Unix(),
		Deleted:   0,
	},

	// 基础资料自定义项子目录
	{
		ID:        9011,
		Name:      "圈舍类型",
		Path:      "/basics/custom/shedtype",
		Level:     3,
		Hash:      "basics",
		Redirect:  "",
		Component: "/pages/basics/custom/shedtype",
		IsSub:     true,
		HasSub:    false,
		Single:    false,
		ParentId:  901,
		TenantId:  DefaultTenant,
		CreatedAt: time.Now().Unix(),
		UpdatedAt: time.Now().Unix(),
		Deleted:   0,
	},
	{
		ID:        9012,
		Name:      "牛只品种",
		Path:      "/basics/custom/cattlebreed",
		Level:     3,
		Hash:      "basics",
		Redirect:  "",
		Component: "/pages/basics/custom/cattlebreed",
		IsSub:     true,
		HasSub:    false,
		Single:    false,
		ParentId:  901,
		TenantId:  DefaultTenant,
		CreatedAt: time.Now().Unix(),
		UpdatedAt: time.Now().Unix(),
		Deleted:   0,
	},
	{
		ID:        9013,
		Name:      "毛色",
		Path:      "/basics/custom/haircolor",
		Level:     3,
		Hash:      "basics",
		Redirect:  "",
		Component: "/pages/basics/custom/haircolor",
		IsSub:     true,
		HasSub:    false,
		Single:    false,
		ParentId:  901,
		TenantId:  DefaultTenant,
		CreatedAt: time.Now().Unix(),
		UpdatedAt: time.Now().Unix(),
		Deleted:   0,
	},
	{
		ID:        9014,
		Name:      "转群原因",
		Path:      "/basics/custom/movereason",
		Level:     3,
		Hash:      "basics",
		Redirect:  "",
		Component: "/pages/basics/custom/movereason",
		IsSub:     true,
		HasSub:    false,
		Single:    false,
		ParentId:  901,
		TenantId:  DefaultTenant,
		CreatedAt: time.Now().Unix(),
		UpdatedAt: time.Now().Unix(),
		Deleted:   0,
	},
	{
		ID:        9015,
		Name:      "流产原因",
		Path:      "/basics/custom/abortionreason",
		Level:     3,
		Hash:      "basics",
		Redirect:  "",
		Component: "/pages/basics/custom/abortionreason",
		IsSub:     true,
		HasSub:    false,
		Single:    false,
		ParentId:  901,
		TenantId:  DefaultTenant,
		CreatedAt: time.Now().Unix(),
		UpdatedAt: time.Now().Unix(),
		Deleted:   0,
	},
	{
		ID:        9016,
		Name:      "职务",
		Path:      "/basics/custom/position",
		Level:     3,
		Hash:      "basics",
		Redirect:  "",
		Component: "/pages/basics/custom/position",
		IsSub:     true,
		HasSub:    false,
		Single:    false,
		ParentId:  901,
		TenantId:  DefaultTenant,
		CreatedAt: time.Now().Unix(),
		UpdatedAt: time.Now().Unix(),
		Deleted:   0,
	},
	{
		ID:        9017,
		Name:      "自定义",
		Path:      "/basics/custom/custom",
		Level:     3,
		Hash:      "basics",
		Redirect:  "",
		Component: "/pages/basics/custom/custom",
		IsSub:     true,
		HasSub:    false,
		Single:    false,
		ParentId:  901,
		TenantId:  DefaultTenant,
		CreatedAt: time.Now().Unix(),
		UpdatedAt: time.Now().Unix(),
		Deleted:   0,
	},

	// 基础资料生产管理子目录
	{
		ID:        9041,
		Name:      "饲料信息",
		Path:      "/basics/pm/feed",
		Level:     3,
		Hash:      "basics",
		Redirect:  "",
		Component: "/pages/basics/pm/feed",
		IsSub:     true,
		HasSub:    false,
		Single:    false,
		ParentId:  904,
		TenantId:  DefaultTenant,
		CreatedAt: time.Now().Unix(),
		UpdatedAt: time.Now().Unix(),
		Deleted:   0,
	},
	{
		ID:        9042,
		Name:      "兽药信息",
		Path:      "/basics/pm/drugs",
		Level:     3,
		Hash:      "basics",
		Redirect:  "",
		Component: "/pages/basics/pm/drugs",
		IsSub:     true,
		HasSub:    false,
		Single:    false,
		ParentId:  904,
		TenantId:  DefaultTenant,
		CreatedAt: time.Now().Unix(),
		UpdatedAt: time.Now().Unix(),
		Deleted:   0,
	},
	{
		ID:        9043,
		Name:      "疫病信息",
		Path:      "/basics/pm/epidemic",
		Level:     3,
		Hash:      "basics",
		Redirect:  "",
		Component: "/pages/basics/pm/epidemic",
		IsSub:     true,
		HasSub:    false,
		Single:    false,
		ParentId:  904,
		TenantId:  DefaultTenant,
		CreatedAt: time.Now().Unix(),
		UpdatedAt: time.Now().Unix(),
		Deleted:   0,
	},
	{
		ID:        9044,
		Name:      "冻精信息",
		Path:      "/basics/pm/semen",
		Level:     3,
		Hash:      "basics",
		Redirect:  "",
		Component: "/pages/basics/pm/semen",
		IsSub:     true,
		HasSub:    false,
		Single:    false,
		ParentId:  904,
		TenantId:  DefaultTenant,
		CreatedAt: time.Now().Unix(),
		UpdatedAt: time.Now().Unix(),
		Deleted:   0,
	},
	{
		ID:        9045,
		Name:      "繁殖参数",
		Path:      "/basics/pm/parameters",
		Level:     3,
		Hash:      "basics",
		Redirect:  "",
		Component: "/pages/basics/pm/parameters",
		IsSub:     true,
		HasSub:    false,
		Single:    false,
		ParentId:  904,
		TenantId:  DefaultTenant,
		CreatedAt: time.Now().Unix(),
		UpdatedAt: time.Now().Unix(),
		Deleted:   0,
	},
	{
		ID:        9046,
		Name:      "自定义",
		Path:      "/basics/pm/custom",
		Level:     3,
		Hash:      "basics",
		Redirect:  "",
		Component: "/pages/basics/pm/custom",
		IsSub:     true,
		HasSub:    false,
		Single:    false,
		ParentId:  904,
		TenantId:  DefaultTenant,
		CreatedAt: time.Now().Unix(),
		UpdatedAt: time.Now().Unix(),
		Deleted:   0,
	},
}
