// Code generated by entc, DO NOT EDIT.

package ent

import (
	"cattleai/ent/abortiontype"
	"context"
	"errors"
	"fmt"

	"github.com/facebook/ent/dialect/sql/sqlgraph"
	"github.com/facebook/ent/schema/field"
)

// AbortionTypeCreate is the builder for creating a AbortionType entity.
type AbortionTypeCreate struct {
	config
	mutation *AbortionTypeMutation
	hooks    []Hook
}

// SetName sets the name field.
func (atc *AbortionTypeCreate) SetName(s string) *AbortionTypeCreate {
	atc.mutation.SetName(s)
	return atc
}

// Mutation returns the AbortionTypeMutation object of the builder.
func (atc *AbortionTypeCreate) Mutation() *AbortionTypeMutation {
	return atc.mutation
}

// Save creates the AbortionType in the database.
func (atc *AbortionTypeCreate) Save(ctx context.Context) (*AbortionType, error) {
	var (
		err  error
		node *AbortionType
	)
	if len(atc.hooks) == 0 {
		if err = atc.check(); err != nil {
			return nil, err
		}
		node, err = atc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*AbortionTypeMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = atc.check(); err != nil {
				return nil, err
			}
			atc.mutation = mutation
			node, err = atc.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(atc.hooks) - 1; i >= 0; i-- {
			mut = atc.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, atc.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (atc *AbortionTypeCreate) SaveX(ctx context.Context) *AbortionType {
	v, err := atc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// check runs all checks and user-defined validators on the builder.
func (atc *AbortionTypeCreate) check() error {
	if _, ok := atc.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New("ent: missing required field \"name\"")}
	}
	if v, ok := atc.mutation.Name(); ok {
		if err := abortiontype.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf("ent: validator failed for field \"name\": %w", err)}
		}
	}
	return nil
}

func (atc *AbortionTypeCreate) sqlSave(ctx context.Context) (*AbortionType, error) {
	_node, _spec := atc.createSpec()
	if err := sqlgraph.CreateNode(ctx, atc.driver, _spec); err != nil {
		if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	return _node, nil
}

func (atc *AbortionTypeCreate) createSpec() (*AbortionType, *sqlgraph.CreateSpec) {
	var (
		_node = &AbortionType{config: atc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: abortiontype.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt64,
				Column: abortiontype.FieldID,
			},
		}
	)
	if value, ok := atc.mutation.Name(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: abortiontype.FieldName,
		})
		_node.Name = value
	}
	return _node, _spec
}

// AbortionTypeCreateBulk is the builder for creating a bulk of AbortionType entities.
type AbortionTypeCreateBulk struct {
	config
	builders []*AbortionTypeCreate
}

// Save creates the AbortionType entities in the database.
func (atcb *AbortionTypeCreateBulk) Save(ctx context.Context) ([]*AbortionType, error) {
	specs := make([]*sqlgraph.CreateSpec, len(atcb.builders))
	nodes := make([]*AbortionType, len(atcb.builders))
	mutators := make([]Mutator, len(atcb.builders))
	for i := range atcb.builders {
		func(i int, root context.Context) {
			builder := atcb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AbortionTypeMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, atcb.builders[i+1].mutation)
				} else {
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, atcb.driver, &sqlgraph.BatchCreateSpec{Nodes: specs}); err != nil {
						if cerr, ok := isSQLConstraintError(err); ok {
							err = cerr
						}
					}
				}
				mutation.done = true
				if err != nil {
					return nil, err
				}
				id := specs[i].ID.Value.(int64)
				nodes[i].ID = int64(id)
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, atcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX calls Save and panics if Save returns an error.
func (atcb *AbortionTypeCreateBulk) SaveX(ctx context.Context) []*AbortionType {
	v, err := atcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}
