// Code generated by entc, DO NOT EDIT.

package ent

import (
	"cattleai/ent/breedingtype"
	"cattleai/ent/predicate"
	"context"
	"errors"
	"fmt"
	"math"

	"github.com/facebook/ent/dialect/sql"
	"github.com/facebook/ent/dialect/sql/sqlgraph"
	"github.com/facebook/ent/schema/field"
)

// BreedingTypeQuery is the builder for querying BreedingType entities.
type BreedingTypeQuery struct {
	config
	limit      *int
	offset     *int
	order      []OrderFunc
	unique     []string
	predicates []predicate.BreedingType
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the builder.
func (btq *BreedingTypeQuery) Where(ps ...predicate.BreedingType) *BreedingTypeQuery {
	btq.predicates = append(btq.predicates, ps...)
	return btq
}

// Limit adds a limit step to the query.
func (btq *BreedingTypeQuery) Limit(limit int) *BreedingTypeQuery {
	btq.limit = &limit
	return btq
}

// Offset adds an offset step to the query.
func (btq *BreedingTypeQuery) Offset(offset int) *BreedingTypeQuery {
	btq.offset = &offset
	return btq
}

// Order adds an order step to the query.
func (btq *BreedingTypeQuery) Order(o ...OrderFunc) *BreedingTypeQuery {
	btq.order = append(btq.order, o...)
	return btq
}

// First returns the first BreedingType entity in the query. Returns *NotFoundError when no breedingtype was found.
func (btq *BreedingTypeQuery) First(ctx context.Context) (*BreedingType, error) {
	nodes, err := btq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{breedingtype.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (btq *BreedingTypeQuery) FirstX(ctx context.Context) *BreedingType {
	node, err := btq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first BreedingType id in the query. Returns *NotFoundError when no id was found.
func (btq *BreedingTypeQuery) FirstID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = btq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{breedingtype.Label}
		return
	}
	return ids[0], nil
}

// FirstXID is like FirstID, but panics if an error occurs.
func (btq *BreedingTypeQuery) FirstXID(ctx context.Context) int64 {
	id, err := btq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns the only BreedingType entity in the query, returns an error if not exactly one entity was returned.
func (btq *BreedingTypeQuery) Only(ctx context.Context) (*BreedingType, error) {
	nodes, err := btq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{breedingtype.Label}
	default:
		return nil, &NotSingularError{breedingtype.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (btq *BreedingTypeQuery) OnlyX(ctx context.Context) *BreedingType {
	node, err := btq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID returns the only BreedingType id in the query, returns an error if not exactly one id was returned.
func (btq *BreedingTypeQuery) OnlyID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = btq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{breedingtype.Label}
	default:
		err = &NotSingularError{breedingtype.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (btq *BreedingTypeQuery) OnlyIDX(ctx context.Context) int64 {
	id, err := btq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of BreedingTypes.
func (btq *BreedingTypeQuery) All(ctx context.Context) ([]*BreedingType, error) {
	if err := btq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return btq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (btq *BreedingTypeQuery) AllX(ctx context.Context) []*BreedingType {
	nodes, err := btq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of BreedingType ids.
func (btq *BreedingTypeQuery) IDs(ctx context.Context) ([]int64, error) {
	var ids []int64
	if err := btq.Select(breedingtype.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (btq *BreedingTypeQuery) IDsX(ctx context.Context) []int64 {
	ids, err := btq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (btq *BreedingTypeQuery) Count(ctx context.Context) (int, error) {
	if err := btq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return btq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (btq *BreedingTypeQuery) CountX(ctx context.Context) int {
	count, err := btq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (btq *BreedingTypeQuery) Exist(ctx context.Context) (bool, error) {
	if err := btq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return btq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (btq *BreedingTypeQuery) ExistX(ctx context.Context) bool {
	exist, err := btq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the query builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (btq *BreedingTypeQuery) Clone() *BreedingTypeQuery {
	return &BreedingTypeQuery{
		config:     btq.config,
		limit:      btq.limit,
		offset:     btq.offset,
		order:      append([]OrderFunc{}, btq.order...),
		unique:     append([]string{}, btq.unique...),
		predicates: append([]predicate.BreedingType{}, btq.predicates...),
		// clone intermediate query.
		sql:  btq.sql.Clone(),
		path: btq.path,
	}
}

// GroupBy used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Name string `json:"name,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.BreedingType.Query().
//		GroupBy(breedingtype.FieldName).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
//
func (btq *BreedingTypeQuery) GroupBy(field string, fields ...string) *BreedingTypeGroupBy {
	group := &BreedingTypeGroupBy{config: btq.config}
	group.fields = append([]string{field}, fields...)
	group.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := btq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return btq.sqlQuery(), nil
	}
	return group
}

// Select one or more fields from the given query.
//
// Example:
//
//	var v []struct {
//		Name string `json:"name,omitempty"`
//	}
//
//	client.BreedingType.Query().
//		Select(breedingtype.FieldName).
//		Scan(ctx, &v)
//
func (btq *BreedingTypeQuery) Select(field string, fields ...string) *BreedingTypeSelect {
	selector := &BreedingTypeSelect{config: btq.config}
	selector.fields = append([]string{field}, fields...)
	selector.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := btq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return btq.sqlQuery(), nil
	}
	return selector
}

func (btq *BreedingTypeQuery) prepareQuery(ctx context.Context) error {
	if btq.path != nil {
		prev, err := btq.path(ctx)
		if err != nil {
			return err
		}
		btq.sql = prev
	}
	return nil
}

func (btq *BreedingTypeQuery) sqlAll(ctx context.Context) ([]*BreedingType, error) {
	var (
		nodes = []*BreedingType{}
		_spec = btq.querySpec()
	)
	_spec.ScanValues = func() []interface{} {
		node := &BreedingType{config: btq.config}
		nodes = append(nodes, node)
		values := node.scanValues()
		return values
	}
	_spec.Assign = func(values ...interface{}) error {
		if len(nodes) == 0 {
			return fmt.Errorf("ent: Assign called without calling ScanValues")
		}
		node := nodes[len(nodes)-1]
		return node.assignValues(values...)
	}
	if err := sqlgraph.QueryNodes(ctx, btq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (btq *BreedingTypeQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := btq.querySpec()
	return sqlgraph.CountNodes(ctx, btq.driver, _spec)
}

func (btq *BreedingTypeQuery) sqlExist(ctx context.Context) (bool, error) {
	n, err := btq.sqlCount(ctx)
	if err != nil {
		return false, fmt.Errorf("ent: check existence: %v", err)
	}
	return n > 0, nil
}

func (btq *BreedingTypeQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   breedingtype.Table,
			Columns: breedingtype.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt64,
				Column: breedingtype.FieldID,
			},
		},
		From:   btq.sql,
		Unique: true,
	}
	if ps := btq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := btq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := btq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := btq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector, breedingtype.ValidColumn)
			}
		}
	}
	return _spec
}

func (btq *BreedingTypeQuery) sqlQuery() *sql.Selector {
	builder := sql.Dialect(btq.driver.Dialect())
	t1 := builder.Table(breedingtype.Table)
	selector := builder.Select(t1.Columns(breedingtype.Columns...)...).From(t1)
	if btq.sql != nil {
		selector = btq.sql
		selector.Select(selector.Columns(breedingtype.Columns...)...)
	}
	for _, p := range btq.predicates {
		p(selector)
	}
	for _, p := range btq.order {
		p(selector, breedingtype.ValidColumn)
	}
	if offset := btq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := btq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// BreedingTypeGroupBy is the builder for group-by BreedingType entities.
type BreedingTypeGroupBy struct {
	config
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (btgb *BreedingTypeGroupBy) Aggregate(fns ...AggregateFunc) *BreedingTypeGroupBy {
	btgb.fns = append(btgb.fns, fns...)
	return btgb
}

// Scan applies the group-by query and scan the result into the given value.
func (btgb *BreedingTypeGroupBy) Scan(ctx context.Context, v interface{}) error {
	query, err := btgb.path(ctx)
	if err != nil {
		return err
	}
	btgb.sql = query
	return btgb.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (btgb *BreedingTypeGroupBy) ScanX(ctx context.Context, v interface{}) {
	if err := btgb.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from group-by. It is only allowed when querying group-by with one field.
func (btgb *BreedingTypeGroupBy) Strings(ctx context.Context) ([]string, error) {
	if len(btgb.fields) > 1 {
		return nil, errors.New("ent: BreedingTypeGroupBy.Strings is not achievable when grouping more than 1 field")
	}
	var v []string
	if err := btgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (btgb *BreedingTypeGroupBy) StringsX(ctx context.Context) []string {
	v, err := btgb.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from group-by. It is only allowed when querying group-by with one field.
func (btgb *BreedingTypeGroupBy) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = btgb.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{breedingtype.Label}
	default:
		err = fmt.Errorf("ent: BreedingTypeGroupBy.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (btgb *BreedingTypeGroupBy) StringX(ctx context.Context) string {
	v, err := btgb.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from group-by. It is only allowed when querying group-by with one field.
func (btgb *BreedingTypeGroupBy) Ints(ctx context.Context) ([]int, error) {
	if len(btgb.fields) > 1 {
		return nil, errors.New("ent: BreedingTypeGroupBy.Ints is not achievable when grouping more than 1 field")
	}
	var v []int
	if err := btgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (btgb *BreedingTypeGroupBy) IntsX(ctx context.Context) []int {
	v, err := btgb.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from group-by. It is only allowed when querying group-by with one field.
func (btgb *BreedingTypeGroupBy) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = btgb.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{breedingtype.Label}
	default:
		err = fmt.Errorf("ent: BreedingTypeGroupBy.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (btgb *BreedingTypeGroupBy) IntX(ctx context.Context) int {
	v, err := btgb.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from group-by. It is only allowed when querying group-by with one field.
func (btgb *BreedingTypeGroupBy) Float64s(ctx context.Context) ([]float64, error) {
	if len(btgb.fields) > 1 {
		return nil, errors.New("ent: BreedingTypeGroupBy.Float64s is not achievable when grouping more than 1 field")
	}
	var v []float64
	if err := btgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (btgb *BreedingTypeGroupBy) Float64sX(ctx context.Context) []float64 {
	v, err := btgb.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from group-by. It is only allowed when querying group-by with one field.
func (btgb *BreedingTypeGroupBy) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = btgb.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{breedingtype.Label}
	default:
		err = fmt.Errorf("ent: BreedingTypeGroupBy.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (btgb *BreedingTypeGroupBy) Float64X(ctx context.Context) float64 {
	v, err := btgb.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from group-by. It is only allowed when querying group-by with one field.
func (btgb *BreedingTypeGroupBy) Bools(ctx context.Context) ([]bool, error) {
	if len(btgb.fields) > 1 {
		return nil, errors.New("ent: BreedingTypeGroupBy.Bools is not achievable when grouping more than 1 field")
	}
	var v []bool
	if err := btgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (btgb *BreedingTypeGroupBy) BoolsX(ctx context.Context) []bool {
	v, err := btgb.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from group-by. It is only allowed when querying group-by with one field.
func (btgb *BreedingTypeGroupBy) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = btgb.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{breedingtype.Label}
	default:
		err = fmt.Errorf("ent: BreedingTypeGroupBy.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (btgb *BreedingTypeGroupBy) BoolX(ctx context.Context) bool {
	v, err := btgb.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (btgb *BreedingTypeGroupBy) sqlScan(ctx context.Context, v interface{}) error {
	for _, f := range btgb.fields {
		if !breedingtype.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for group-by", f)}
		}
	}
	selector := btgb.sqlQuery()
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := btgb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (btgb *BreedingTypeGroupBy) sqlQuery() *sql.Selector {
	selector := btgb.sql
	columns := make([]string, 0, len(btgb.fields)+len(btgb.fns))
	columns = append(columns, btgb.fields...)
	for _, fn := range btgb.fns {
		columns = append(columns, fn(selector, breedingtype.ValidColumn))
	}
	return selector.Select(columns...).GroupBy(btgb.fields...)
}

// BreedingTypeSelect is the builder for select fields of BreedingType entities.
type BreedingTypeSelect struct {
	config
	fields []string
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Scan applies the selector query and scan the result into the given value.
func (bts *BreedingTypeSelect) Scan(ctx context.Context, v interface{}) error {
	query, err := bts.path(ctx)
	if err != nil {
		return err
	}
	bts.sql = query
	return bts.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (bts *BreedingTypeSelect) ScanX(ctx context.Context, v interface{}) {
	if err := bts.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from selector. It is only allowed when selecting one field.
func (bts *BreedingTypeSelect) Strings(ctx context.Context) ([]string, error) {
	if len(bts.fields) > 1 {
		return nil, errors.New("ent: BreedingTypeSelect.Strings is not achievable when selecting more than 1 field")
	}
	var v []string
	if err := bts.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (bts *BreedingTypeSelect) StringsX(ctx context.Context) []string {
	v, err := bts.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from selector. It is only allowed when selecting one field.
func (bts *BreedingTypeSelect) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = bts.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{breedingtype.Label}
	default:
		err = fmt.Errorf("ent: BreedingTypeSelect.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (bts *BreedingTypeSelect) StringX(ctx context.Context) string {
	v, err := bts.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from selector. It is only allowed when selecting one field.
func (bts *BreedingTypeSelect) Ints(ctx context.Context) ([]int, error) {
	if len(bts.fields) > 1 {
		return nil, errors.New("ent: BreedingTypeSelect.Ints is not achievable when selecting more than 1 field")
	}
	var v []int
	if err := bts.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (bts *BreedingTypeSelect) IntsX(ctx context.Context) []int {
	v, err := bts.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from selector. It is only allowed when selecting one field.
func (bts *BreedingTypeSelect) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = bts.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{breedingtype.Label}
	default:
		err = fmt.Errorf("ent: BreedingTypeSelect.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (bts *BreedingTypeSelect) IntX(ctx context.Context) int {
	v, err := bts.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from selector. It is only allowed when selecting one field.
func (bts *BreedingTypeSelect) Float64s(ctx context.Context) ([]float64, error) {
	if len(bts.fields) > 1 {
		return nil, errors.New("ent: BreedingTypeSelect.Float64s is not achievable when selecting more than 1 field")
	}
	var v []float64
	if err := bts.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (bts *BreedingTypeSelect) Float64sX(ctx context.Context) []float64 {
	v, err := bts.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from selector. It is only allowed when selecting one field.
func (bts *BreedingTypeSelect) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = bts.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{breedingtype.Label}
	default:
		err = fmt.Errorf("ent: BreedingTypeSelect.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (bts *BreedingTypeSelect) Float64X(ctx context.Context) float64 {
	v, err := bts.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from selector. It is only allowed when selecting one field.
func (bts *BreedingTypeSelect) Bools(ctx context.Context) ([]bool, error) {
	if len(bts.fields) > 1 {
		return nil, errors.New("ent: BreedingTypeSelect.Bools is not achievable when selecting more than 1 field")
	}
	var v []bool
	if err := bts.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (bts *BreedingTypeSelect) BoolsX(ctx context.Context) []bool {
	v, err := bts.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from selector. It is only allowed when selecting one field.
func (bts *BreedingTypeSelect) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = bts.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{breedingtype.Label}
	default:
		err = fmt.Errorf("ent: BreedingTypeSelect.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (bts *BreedingTypeSelect) BoolX(ctx context.Context) bool {
	v, err := bts.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (bts *BreedingTypeSelect) sqlScan(ctx context.Context, v interface{}) error {
	for _, f := range bts.fields {
		if !breedingtype.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for selection", f)}
		}
	}
	rows := &sql.Rows{}
	query, args := bts.sqlQuery().Query()
	if err := bts.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (bts *BreedingTypeSelect) sqlQuery() sql.Querier {
	selector := bts.sql
	selector.Select(selector.Columns(bts.fields...)...)
	return selector
}
