// Code generated by ent, DO NOT EDIT.

package ent

import (
	"cattleai/ent/breedingtype"
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// BreedingTypeCreate is the builder for creating a BreedingType entity.
type BreedingTypeCreate struct {
	config
	mutation *BreedingTypeMutation
	hooks    []Hook
}

// SetName sets the "name" field.
func (btc *BreedingTypeCreate) SetName(s string) *BreedingTypeCreate {
	btc.mutation.SetName(s)
	return btc
}

// Mutation returns the BreedingTypeMutation object of the builder.
func (btc *BreedingTypeCreate) Mutation() *BreedingTypeMutation {
	return btc.mutation
}

// Save creates the BreedingType in the database.
func (btc *BreedingTypeCreate) Save(ctx context.Context) (*BreedingType, error) {
	var (
		err  error
		node *BreedingType
	)
	if len(btc.hooks) == 0 {
		if err = btc.check(); err != nil {
			return nil, err
		}
		node, err = btc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*BreedingTypeMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = btc.check(); err != nil {
				return nil, err
			}
			btc.mutation = mutation
			if node, err = btc.sqlSave(ctx); err != nil {
				return nil, err
			}
			mutation.id = &node.ID
			mutation.done = true
			return node, err
		})
		for i := len(btc.hooks) - 1; i >= 0; i-- {
			if btc.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = btc.hooks[i](mut)
		}
		v, err := mut.Mutate(ctx, btc.mutation)
		if err != nil {
			return nil, err
		}
		nv, ok := v.(*BreedingType)
		if !ok {
			return nil, fmt.Errorf("unexpected node type %T returned from BreedingTypeMutation", v)
		}
		node = nv
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (btc *BreedingTypeCreate) SaveX(ctx context.Context) *BreedingType {
	v, err := btc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (btc *BreedingTypeCreate) Exec(ctx context.Context) error {
	_, err := btc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (btc *BreedingTypeCreate) ExecX(ctx context.Context) {
	if err := btc.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (btc *BreedingTypeCreate) check() error {
	if _, ok := btc.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "BreedingType.name"`)}
	}
	if v, ok := btc.mutation.Name(); ok {
		if err := breedingtype.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "BreedingType.name": %w`, err)}
		}
	}
	return nil
}

func (btc *BreedingTypeCreate) sqlSave(ctx context.Context) (*BreedingType, error) {
	_node, _spec := btc.createSpec()
	if err := sqlgraph.CreateNode(ctx, btc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	return _node, nil
}

func (btc *BreedingTypeCreate) createSpec() (*BreedingType, *sqlgraph.CreateSpec) {
	var (
		_node = &BreedingType{config: btc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: breedingtype.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: breedingtype.FieldID,
			},
		}
	)
	if value, ok := btc.mutation.Name(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: breedingtype.FieldName,
		})
		_node.Name = value
	}
	return _node, _spec
}

// BreedingTypeCreateBulk is the builder for creating many BreedingType entities in bulk.
type BreedingTypeCreateBulk struct {
	config
	builders []*BreedingTypeCreate
}

// Save creates the BreedingType entities in the database.
func (btcb *BreedingTypeCreateBulk) Save(ctx context.Context) ([]*BreedingType, error) {
	specs := make([]*sqlgraph.CreateSpec, len(btcb.builders))
	nodes := make([]*BreedingType, len(btcb.builders))
	mutators := make([]Mutator, len(btcb.builders))
	for i := range btcb.builders {
		func(i int, root context.Context) {
			builder := btcb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*BreedingTypeMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, btcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, btcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, btcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (btcb *BreedingTypeCreateBulk) SaveX(ctx context.Context) []*BreedingType {
	v, err := btcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (btcb *BreedingTypeCreateBulk) Exec(ctx context.Context) error {
	_, err := btcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (btcb *BreedingTypeCreateBulk) ExecX(ctx context.Context) {
	if err := btcb.Exec(ctx); err != nil {
		panic(err)
	}
}
