// Code generated by ent, DO NOT EDIT.

package ent

import (
	"cattleai/ent/cattlegrowsrate"
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// CattleGrowsRateCreate is the builder for creating a CattleGrowsRate entity.
type CattleGrowsRateCreate struct {
	config
	mutation *CattleGrowsRateMutation
	hooks    []Hook
}

// SetName sets the "name" field.
func (cgrc *CattleGrowsRateCreate) SetName(s string) *CattleGrowsRateCreate {
	cgrc.mutation.SetName(s)
	return cgrc
}

// SetNillableName sets the "name" field if the given value is not nil.
func (cgrc *CattleGrowsRateCreate) SetNillableName(s *string) *CattleGrowsRateCreate {
	if s != nil {
		cgrc.SetName(*s)
	}
	return cgrc
}

// SetEarNumber sets the "earNumber" field.
func (cgrc *CattleGrowsRateCreate) SetEarNumber(s string) *CattleGrowsRateCreate {
	cgrc.mutation.SetEarNumber(s)
	return cgrc
}

// SetShedName sets the "shedName" field.
func (cgrc *CattleGrowsRateCreate) SetShedName(s string) *CattleGrowsRateCreate {
	cgrc.mutation.SetShedName(s)
	return cgrc
}

// SetRatedAt sets the "ratedAt" field.
func (cgrc *CattleGrowsRateCreate) SetRatedAt(i int64) *CattleGrowsRateCreate {
	cgrc.mutation.SetRatedAt(i)
	return cgrc
}

// SetRatedBy sets the "ratedBy" field.
func (cgrc *CattleGrowsRateCreate) SetRatedBy(s string) *CattleGrowsRateCreate {
	cgrc.mutation.SetRatedBy(s)
	return cgrc
}

// SetRate sets the "rate" field.
func (cgrc *CattleGrowsRateCreate) SetRate(i int) *CattleGrowsRateCreate {
	cgrc.mutation.SetRate(i)
	return cgrc
}

// SetTenantId sets the "tenantId" field.
func (cgrc *CattleGrowsRateCreate) SetTenantId(i int64) *CattleGrowsRateCreate {
	cgrc.mutation.SetTenantId(i)
	return cgrc
}

// SetTenantName sets the "tenantName" field.
func (cgrc *CattleGrowsRateCreate) SetTenantName(s string) *CattleGrowsRateCreate {
	cgrc.mutation.SetTenantName(s)
	return cgrc
}

// SetRemarks sets the "remarks" field.
func (cgrc *CattleGrowsRateCreate) SetRemarks(s string) *CattleGrowsRateCreate {
	cgrc.mutation.SetRemarks(s)
	return cgrc
}

// SetCreatedAt sets the "createdAt" field.
func (cgrc *CattleGrowsRateCreate) SetCreatedAt(i int64) *CattleGrowsRateCreate {
	cgrc.mutation.SetCreatedAt(i)
	return cgrc
}

// SetUpdatedAt sets the "updatedAt" field.
func (cgrc *CattleGrowsRateCreate) SetUpdatedAt(i int64) *CattleGrowsRateCreate {
	cgrc.mutation.SetUpdatedAt(i)
	return cgrc
}

// SetDeleted sets the "deleted" field.
func (cgrc *CattleGrowsRateCreate) SetDeleted(i int) *CattleGrowsRateCreate {
	cgrc.mutation.SetDeleted(i)
	return cgrc
}

// Mutation returns the CattleGrowsRateMutation object of the builder.
func (cgrc *CattleGrowsRateCreate) Mutation() *CattleGrowsRateMutation {
	return cgrc.mutation
}

// Save creates the CattleGrowsRate in the database.
func (cgrc *CattleGrowsRateCreate) Save(ctx context.Context) (*CattleGrowsRate, error) {
	var (
		err  error
		node *CattleGrowsRate
	)
	if len(cgrc.hooks) == 0 {
		if err = cgrc.check(); err != nil {
			return nil, err
		}
		node, err = cgrc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*CattleGrowsRateMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = cgrc.check(); err != nil {
				return nil, err
			}
			cgrc.mutation = mutation
			if node, err = cgrc.sqlSave(ctx); err != nil {
				return nil, err
			}
			mutation.id = &node.ID
			mutation.done = true
			return node, err
		})
		for i := len(cgrc.hooks) - 1; i >= 0; i-- {
			if cgrc.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = cgrc.hooks[i](mut)
		}
		v, err := mut.Mutate(ctx, cgrc.mutation)
		if err != nil {
			return nil, err
		}
		nv, ok := v.(*CattleGrowsRate)
		if !ok {
			return nil, fmt.Errorf("unexpected node type %T returned from CattleGrowsRateMutation", v)
		}
		node = nv
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (cgrc *CattleGrowsRateCreate) SaveX(ctx context.Context) *CattleGrowsRate {
	v, err := cgrc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (cgrc *CattleGrowsRateCreate) Exec(ctx context.Context) error {
	_, err := cgrc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (cgrc *CattleGrowsRateCreate) ExecX(ctx context.Context) {
	if err := cgrc.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (cgrc *CattleGrowsRateCreate) check() error {
	if _, ok := cgrc.mutation.EarNumber(); !ok {
		return &ValidationError{Name: "earNumber", err: errors.New(`ent: missing required field "CattleGrowsRate.earNumber"`)}
	}
	if _, ok := cgrc.mutation.ShedName(); !ok {
		return &ValidationError{Name: "shedName", err: errors.New(`ent: missing required field "CattleGrowsRate.shedName"`)}
	}
	if _, ok := cgrc.mutation.RatedAt(); !ok {
		return &ValidationError{Name: "ratedAt", err: errors.New(`ent: missing required field "CattleGrowsRate.ratedAt"`)}
	}
	if _, ok := cgrc.mutation.RatedBy(); !ok {
		return &ValidationError{Name: "ratedBy", err: errors.New(`ent: missing required field "CattleGrowsRate.ratedBy"`)}
	}
	if _, ok := cgrc.mutation.Rate(); !ok {
		return &ValidationError{Name: "rate", err: errors.New(`ent: missing required field "CattleGrowsRate.rate"`)}
	}
	if _, ok := cgrc.mutation.TenantId(); !ok {
		return &ValidationError{Name: "tenantId", err: errors.New(`ent: missing required field "CattleGrowsRate.tenantId"`)}
	}
	if _, ok := cgrc.mutation.TenantName(); !ok {
		return &ValidationError{Name: "tenantName", err: errors.New(`ent: missing required field "CattleGrowsRate.tenantName"`)}
	}
	if _, ok := cgrc.mutation.Remarks(); !ok {
		return &ValidationError{Name: "remarks", err: errors.New(`ent: missing required field "CattleGrowsRate.remarks"`)}
	}
	if _, ok := cgrc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "createdAt", err: errors.New(`ent: missing required field "CattleGrowsRate.createdAt"`)}
	}
	if _, ok := cgrc.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updatedAt", err: errors.New(`ent: missing required field "CattleGrowsRate.updatedAt"`)}
	}
	if _, ok := cgrc.mutation.Deleted(); !ok {
		return &ValidationError{Name: "deleted", err: errors.New(`ent: missing required field "CattleGrowsRate.deleted"`)}
	}
	return nil
}

func (cgrc *CattleGrowsRateCreate) sqlSave(ctx context.Context) (*CattleGrowsRate, error) {
	_node, _spec := cgrc.createSpec()
	if err := sqlgraph.CreateNode(ctx, cgrc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	return _node, nil
}

func (cgrc *CattleGrowsRateCreate) createSpec() (*CattleGrowsRate, *sqlgraph.CreateSpec) {
	var (
		_node = &CattleGrowsRate{config: cgrc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: cattlegrowsrate.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: cattlegrowsrate.FieldID,
			},
		}
	)
	if value, ok := cgrc.mutation.Name(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: cattlegrowsrate.FieldName,
		})
		_node.Name = value
	}
	if value, ok := cgrc.mutation.EarNumber(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: cattlegrowsrate.FieldEarNumber,
		})
		_node.EarNumber = value
	}
	if value, ok := cgrc.mutation.ShedName(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: cattlegrowsrate.FieldShedName,
		})
		_node.ShedName = value
	}
	if value, ok := cgrc.mutation.RatedAt(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeInt64,
			Value:  value,
			Column: cattlegrowsrate.FieldRatedAt,
		})
		_node.RatedAt = value
	}
	if value, ok := cgrc.mutation.RatedBy(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: cattlegrowsrate.FieldRatedBy,
		})
		_node.RatedBy = value
	}
	if value, ok := cgrc.mutation.Rate(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: cattlegrowsrate.FieldRate,
		})
		_node.Rate = value
	}
	if value, ok := cgrc.mutation.TenantId(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeInt64,
			Value:  value,
			Column: cattlegrowsrate.FieldTenantId,
		})
		_node.TenantId = value
	}
	if value, ok := cgrc.mutation.TenantName(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: cattlegrowsrate.FieldTenantName,
		})
		_node.TenantName = value
	}
	if value, ok := cgrc.mutation.Remarks(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: cattlegrowsrate.FieldRemarks,
		})
		_node.Remarks = value
	}
	if value, ok := cgrc.mutation.CreatedAt(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeInt64,
			Value:  value,
			Column: cattlegrowsrate.FieldCreatedAt,
		})
		_node.CreatedAt = value
	}
	if value, ok := cgrc.mutation.UpdatedAt(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeInt64,
			Value:  value,
			Column: cattlegrowsrate.FieldUpdatedAt,
		})
		_node.UpdatedAt = value
	}
	if value, ok := cgrc.mutation.Deleted(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: cattlegrowsrate.FieldDeleted,
		})
		_node.Deleted = value
	}
	return _node, _spec
}

// CattleGrowsRateCreateBulk is the builder for creating many CattleGrowsRate entities in bulk.
type CattleGrowsRateCreateBulk struct {
	config
	builders []*CattleGrowsRateCreate
}

// Save creates the CattleGrowsRate entities in the database.
func (cgrcb *CattleGrowsRateCreateBulk) Save(ctx context.Context) ([]*CattleGrowsRate, error) {
	specs := make([]*sqlgraph.CreateSpec, len(cgrcb.builders))
	nodes := make([]*CattleGrowsRate, len(cgrcb.builders))
	mutators := make([]Mutator, len(cgrcb.builders))
	for i := range cgrcb.builders {
		func(i int, root context.Context) {
			builder := cgrcb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*CattleGrowsRateMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, cgrcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, cgrcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, cgrcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (cgrcb *CattleGrowsRateCreateBulk) SaveX(ctx context.Context) []*CattleGrowsRate {
	v, err := cgrcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (cgrcb *CattleGrowsRateCreateBulk) Exec(ctx context.Context) error {
	_, err := cgrcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (cgrcb *CattleGrowsRateCreateBulk) ExecX(ctx context.Context) {
	if err := cgrcb.Exec(ctx); err != nil {
		panic(err)
	}
}
