// Code generated by entc, DO NOT EDIT.

package ent

import (
	"cattleai/ent/concentrateprocess"
	"fmt"
	"strings"

	"github.com/facebook/ent/dialect/sql"
)

// ConcentrateProcess is the model entity for the ConcentrateProcess schema.
type ConcentrateProcess struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// ConcentrateId holds the value of the "concentrateId" field.
	ConcentrateId int64 `json:"concentrateId,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Date holds the value of the "date" field.
	Date int64 `json:"date,omitempty"`
	// Count holds the value of the "count" field.
	Count int64 `json:"count,omitempty"`
	// In holds the value of the "in" field.
	In int64 `json:"in,omitempty"`
	// UserName holds the value of the "userName" field.
	UserName string `json:"userName,omitempty"`
	// TenantId holds the value of the "tenantId" field.
	TenantId int64 `json:"tenantId,omitempty"`
	// TenantName holds the value of the "tenantName" field.
	TenantName string `json:"tenantName,omitempty"`
	// FarmId holds the value of the "farmId" field.
	FarmId int64 `json:"farmId,omitempty"`
	// FarmName holds the value of the "farmName" field.
	FarmName string `json:"farmName,omitempty"`
	// Remarks holds the value of the "remarks" field.
	Remarks string `json:"remarks,omitempty"`
	// CreatedAt holds the value of the "createdAt" field.
	CreatedAt int64 `json:"createdAt,omitempty"`
	// UpdatedAt holds the value of the "updatedAt" field.
	UpdatedAt int64 `json:"updatedAt,omitempty"`
	// Deleted holds the value of the "deleted" field.
	Deleted int `json:"deleted,omitempty"`
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ConcentrateProcess) scanValues() []interface{} {
	return []interface{}{
		&sql.NullInt64{},  // id
		&sql.NullInt64{},  // concentrateId
		&sql.NullString{}, // name
		&sql.NullInt64{},  // date
		&sql.NullInt64{},  // count
		&sql.NullInt64{},  // in
		&sql.NullString{}, // userName
		&sql.NullInt64{},  // tenantId
		&sql.NullString{}, // tenantName
		&sql.NullInt64{},  // farmId
		&sql.NullString{}, // farmName
		&sql.NullString{}, // remarks
		&sql.NullInt64{},  // createdAt
		&sql.NullInt64{},  // updatedAt
		&sql.NullInt64{},  // deleted
	}
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ConcentrateProcess fields.
func (cp *ConcentrateProcess) assignValues(values ...interface{}) error {
	if m, n := len(values), len(concentrateprocess.Columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	value, ok := values[0].(*sql.NullInt64)
	if !ok {
		return fmt.Errorf("unexpected type %T for field id", value)
	}
	cp.ID = int64(value.Int64)
	values = values[1:]
	if value, ok := values[0].(*sql.NullInt64); !ok {
		return fmt.Errorf("unexpected type %T for field concentrateId", values[0])
	} else if value.Valid {
		cp.ConcentrateId = value.Int64
	}
	if value, ok := values[1].(*sql.NullString); !ok {
		return fmt.Errorf("unexpected type %T for field name", values[1])
	} else if value.Valid {
		cp.Name = value.String
	}
	if value, ok := values[2].(*sql.NullInt64); !ok {
		return fmt.Errorf("unexpected type %T for field date", values[2])
	} else if value.Valid {
		cp.Date = value.Int64
	}
	if value, ok := values[3].(*sql.NullInt64); !ok {
		return fmt.Errorf("unexpected type %T for field count", values[3])
	} else if value.Valid {
		cp.Count = value.Int64
	}
	if value, ok := values[4].(*sql.NullInt64); !ok {
		return fmt.Errorf("unexpected type %T for field in", values[4])
	} else if value.Valid {
		cp.In = value.Int64
	}
	if value, ok := values[5].(*sql.NullString); !ok {
		return fmt.Errorf("unexpected type %T for field userName", values[5])
	} else if value.Valid {
		cp.UserName = value.String
	}
	if value, ok := values[6].(*sql.NullInt64); !ok {
		return fmt.Errorf("unexpected type %T for field tenantId", values[6])
	} else if value.Valid {
		cp.TenantId = value.Int64
	}
	if value, ok := values[7].(*sql.NullString); !ok {
		return fmt.Errorf("unexpected type %T for field tenantName", values[7])
	} else if value.Valid {
		cp.TenantName = value.String
	}
	if value, ok := values[8].(*sql.NullInt64); !ok {
		return fmt.Errorf("unexpected type %T for field farmId", values[8])
	} else if value.Valid {
		cp.FarmId = value.Int64
	}
	if value, ok := values[9].(*sql.NullString); !ok {
		return fmt.Errorf("unexpected type %T for field farmName", values[9])
	} else if value.Valid {
		cp.FarmName = value.String
	}
	if value, ok := values[10].(*sql.NullString); !ok {
		return fmt.Errorf("unexpected type %T for field remarks", values[10])
	} else if value.Valid {
		cp.Remarks = value.String
	}
	if value, ok := values[11].(*sql.NullInt64); !ok {
		return fmt.Errorf("unexpected type %T for field createdAt", values[11])
	} else if value.Valid {
		cp.CreatedAt = value.Int64
	}
	if value, ok := values[12].(*sql.NullInt64); !ok {
		return fmt.Errorf("unexpected type %T for field updatedAt", values[12])
	} else if value.Valid {
		cp.UpdatedAt = value.Int64
	}
	if value, ok := values[13].(*sql.NullInt64); !ok {
		return fmt.Errorf("unexpected type %T for field deleted", values[13])
	} else if value.Valid {
		cp.Deleted = int(value.Int64)
	}
	return nil
}

// Update returns a builder for updating this ConcentrateProcess.
// Note that, you need to call ConcentrateProcess.Unwrap() before calling this method, if this ConcentrateProcess
// was returned from a transaction, and the transaction was committed or rolled back.
func (cp *ConcentrateProcess) Update() *ConcentrateProcessUpdateOne {
	return (&ConcentrateProcessClient{config: cp.config}).UpdateOne(cp)
}

// Unwrap unwraps the entity that was returned from a transaction after it was closed,
// so that all next queries will be executed through the driver which created the transaction.
func (cp *ConcentrateProcess) Unwrap() *ConcentrateProcess {
	tx, ok := cp.config.driver.(*txDriver)
	if !ok {
		panic("ent: ConcentrateProcess is not a transactional entity")
	}
	cp.config.driver = tx.drv
	return cp
}

// String implements the fmt.Stringer.
func (cp *ConcentrateProcess) String() string {
	var builder strings.Builder
	builder.WriteString("ConcentrateProcess(")
	builder.WriteString(fmt.Sprintf("id=%v", cp.ID))
	builder.WriteString(", concentrateId=")
	builder.WriteString(fmt.Sprintf("%v", cp.ConcentrateId))
	builder.WriteString(", name=")
	builder.WriteString(cp.Name)
	builder.WriteString(", date=")
	builder.WriteString(fmt.Sprintf("%v", cp.Date))
	builder.WriteString(", count=")
	builder.WriteString(fmt.Sprintf("%v", cp.Count))
	builder.WriteString(", in=")
	builder.WriteString(fmt.Sprintf("%v", cp.In))
	builder.WriteString(", userName=")
	builder.WriteString(cp.UserName)
	builder.WriteString(", tenantId=")
	builder.WriteString(fmt.Sprintf("%v", cp.TenantId))
	builder.WriteString(", tenantName=")
	builder.WriteString(cp.TenantName)
	builder.WriteString(", farmId=")
	builder.WriteString(fmt.Sprintf("%v", cp.FarmId))
	builder.WriteString(", farmName=")
	builder.WriteString(cp.FarmName)
	builder.WriteString(", remarks=")
	builder.WriteString(cp.Remarks)
	builder.WriteString(", createdAt=")
	builder.WriteString(fmt.Sprintf("%v", cp.CreatedAt))
	builder.WriteString(", updatedAt=")
	builder.WriteString(fmt.Sprintf("%v", cp.UpdatedAt))
	builder.WriteString(", deleted=")
	builder.WriteString(fmt.Sprintf("%v", cp.Deleted))
	builder.WriteByte(')')
	return builder.String()
}

// ConcentrateProcesses is a parsable slice of ConcentrateProcess.
type ConcentrateProcesses []*ConcentrateProcess

func (cp ConcentrateProcesses) config(cfg config) {
	for _i := range cp {
		cp[_i].config = cfg
	}
}
