// Code generated by entc, DO NOT EDIT.

package ent

import (
	"cattleai/ent/concentrateformula"
	"cattleai/ent/predicate"
	"context"
	"fmt"

	"github.com/facebook/ent/dialect/sql"
	"github.com/facebook/ent/dialect/sql/sqlgraph"
	"github.com/facebook/ent/schema/field"
)

// ConcentrateFormulaUpdate is the builder for updating ConcentrateFormula entities.
type ConcentrateFormulaUpdate struct {
	config
	hooks      []Hook
	mutation   *ConcentrateFormulaMutation
	predicates []predicate.ConcentrateFormula
}

// Where adds a new predicate for the builder.
func (cfu *ConcentrateFormulaUpdate) Where(ps ...predicate.ConcentrateFormula) *ConcentrateFormulaUpdate {
	cfu.predicates = append(cfu.predicates, ps...)
	return cfu
}

// SetName sets the name field.
func (cfu *ConcentrateFormulaUpdate) SetName(s string) *ConcentrateFormulaUpdate {
	cfu.mutation.SetName(s)
	return cfu
}

// SetCode sets the code field.
func (cfu *ConcentrateFormulaUpdate) SetCode(s string) *ConcentrateFormulaUpdate {
	cfu.mutation.SetCode(s)
	return cfu
}

// SetStatus sets the status field.
func (cfu *ConcentrateFormulaUpdate) SetStatus(i int) *ConcentrateFormulaUpdate {
	cfu.mutation.ResetStatus()
	cfu.mutation.SetStatus(i)
	return cfu
}

// AddStatus adds i to status.
func (cfu *ConcentrateFormulaUpdate) AddStatus(i int) *ConcentrateFormulaUpdate {
	cfu.mutation.AddStatus(i)
	return cfu
}

// SetCreateDate sets the createDate field.
func (cfu *ConcentrateFormulaUpdate) SetCreateDate(i int64) *ConcentrateFormulaUpdate {
	cfu.mutation.ResetCreateDate()
	cfu.mutation.SetCreateDate(i)
	return cfu
}

// AddCreateDate adds i to createDate.
func (cfu *ConcentrateFormulaUpdate) AddCreateDate(i int64) *ConcentrateFormulaUpdate {
	cfu.mutation.AddCreateDate(i)
	return cfu
}

// SetAdjustDate sets the adjustDate field.
func (cfu *ConcentrateFormulaUpdate) SetAdjustDate(i int64) *ConcentrateFormulaUpdate {
	cfu.mutation.ResetAdjustDate()
	cfu.mutation.SetAdjustDate(i)
	return cfu
}

// AddAdjustDate adds i to adjustDate.
func (cfu *ConcentrateFormulaUpdate) AddAdjustDate(i int64) *ConcentrateFormulaUpdate {
	cfu.mutation.AddAdjustDate(i)
	return cfu
}

// SetDisableDate sets the disableDate field.
func (cfu *ConcentrateFormulaUpdate) SetDisableDate(i int64) *ConcentrateFormulaUpdate {
	cfu.mutation.ResetDisableDate()
	cfu.mutation.SetDisableDate(i)
	return cfu
}

// AddDisableDate adds i to disableDate.
func (cfu *ConcentrateFormulaUpdate) AddDisableDate(i int64) *ConcentrateFormulaUpdate {
	cfu.mutation.AddDisableDate(i)
	return cfu
}

// SetCost sets the cost field.
func (cfu *ConcentrateFormulaUpdate) SetCost(i int64) *ConcentrateFormulaUpdate {
	cfu.mutation.ResetCost()
	cfu.mutation.SetCost(i)
	return cfu
}

// AddCost adds i to cost.
func (cfu *ConcentrateFormulaUpdate) AddCost(i int64) *ConcentrateFormulaUpdate {
	cfu.mutation.AddCost(i)
	return cfu
}

// SetTenantId sets the tenantId field.
func (cfu *ConcentrateFormulaUpdate) SetTenantId(i int64) *ConcentrateFormulaUpdate {
	cfu.mutation.ResetTenantId()
	cfu.mutation.SetTenantId(i)
	return cfu
}

// AddTenantId adds i to tenantId.
func (cfu *ConcentrateFormulaUpdate) AddTenantId(i int64) *ConcentrateFormulaUpdate {
	cfu.mutation.AddTenantId(i)
	return cfu
}

// SetTenantName sets the tenantName field.
func (cfu *ConcentrateFormulaUpdate) SetTenantName(s string) *ConcentrateFormulaUpdate {
	cfu.mutation.SetTenantName(s)
	return cfu
}

// SetRemarks sets the remarks field.
func (cfu *ConcentrateFormulaUpdate) SetRemarks(s string) *ConcentrateFormulaUpdate {
	cfu.mutation.SetRemarks(s)
	return cfu
}

// SetCreatedAt sets the createdAt field.
func (cfu *ConcentrateFormulaUpdate) SetCreatedAt(i int64) *ConcentrateFormulaUpdate {
	cfu.mutation.ResetCreatedAt()
	cfu.mutation.SetCreatedAt(i)
	return cfu
}

// AddCreatedAt adds i to createdAt.
func (cfu *ConcentrateFormulaUpdate) AddCreatedAt(i int64) *ConcentrateFormulaUpdate {
	cfu.mutation.AddCreatedAt(i)
	return cfu
}

// SetUpdatedAt sets the updatedAt field.
func (cfu *ConcentrateFormulaUpdate) SetUpdatedAt(i int64) *ConcentrateFormulaUpdate {
	cfu.mutation.ResetUpdatedAt()
	cfu.mutation.SetUpdatedAt(i)
	return cfu
}

// AddUpdatedAt adds i to updatedAt.
func (cfu *ConcentrateFormulaUpdate) AddUpdatedAt(i int64) *ConcentrateFormulaUpdate {
	cfu.mutation.AddUpdatedAt(i)
	return cfu
}

// SetDeleted sets the deleted field.
func (cfu *ConcentrateFormulaUpdate) SetDeleted(i int) *ConcentrateFormulaUpdate {
	cfu.mutation.ResetDeleted()
	cfu.mutation.SetDeleted(i)
	return cfu
}

// AddDeleted adds i to deleted.
func (cfu *ConcentrateFormulaUpdate) AddDeleted(i int) *ConcentrateFormulaUpdate {
	cfu.mutation.AddDeleted(i)
	return cfu
}

// Mutation returns the ConcentrateFormulaMutation object of the builder.
func (cfu *ConcentrateFormulaUpdate) Mutation() *ConcentrateFormulaMutation {
	return cfu.mutation
}

// Save executes the query and returns the number of rows/vertices matched by this operation.
func (cfu *ConcentrateFormulaUpdate) Save(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(cfu.hooks) == 0 {
		affected, err = cfu.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*ConcentrateFormulaMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			cfu.mutation = mutation
			affected, err = cfu.sqlSave(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(cfu.hooks) - 1; i >= 0; i-- {
			mut = cfu.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, cfu.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (cfu *ConcentrateFormulaUpdate) SaveX(ctx context.Context) int {
	affected, err := cfu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (cfu *ConcentrateFormulaUpdate) Exec(ctx context.Context) error {
	_, err := cfu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (cfu *ConcentrateFormulaUpdate) ExecX(ctx context.Context) {
	if err := cfu.Exec(ctx); err != nil {
		panic(err)
	}
}

func (cfu *ConcentrateFormulaUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   concentrateformula.Table,
			Columns: concentrateformula.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt64,
				Column: concentrateformula.FieldID,
			},
		},
	}
	if ps := cfu.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := cfu.mutation.Name(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: concentrateformula.FieldName,
		})
	}
	if value, ok := cfu.mutation.Code(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: concentrateformula.FieldCode,
		})
	}
	if value, ok := cfu.mutation.Status(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: concentrateformula.FieldStatus,
		})
	}
	if value, ok := cfu.mutation.AddedStatus(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: concentrateformula.FieldStatus,
		})
	}
	if value, ok := cfu.mutation.CreateDate(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeInt64,
			Value:  value,
			Column: concentrateformula.FieldCreateDate,
		})
	}
	if value, ok := cfu.mutation.AddedCreateDate(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeInt64,
			Value:  value,
			Column: concentrateformula.FieldCreateDate,
		})
	}
	if value, ok := cfu.mutation.AdjustDate(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeInt64,
			Value:  value,
			Column: concentrateformula.FieldAdjustDate,
		})
	}
	if value, ok := cfu.mutation.AddedAdjustDate(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeInt64,
			Value:  value,
			Column: concentrateformula.FieldAdjustDate,
		})
	}
	if value, ok := cfu.mutation.DisableDate(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeInt64,
			Value:  value,
			Column: concentrateformula.FieldDisableDate,
		})
	}
	if value, ok := cfu.mutation.AddedDisableDate(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeInt64,
			Value:  value,
			Column: concentrateformula.FieldDisableDate,
		})
	}
	if value, ok := cfu.mutation.Cost(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeInt64,
			Value:  value,
			Column: concentrateformula.FieldCost,
		})
	}
	if value, ok := cfu.mutation.AddedCost(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeInt64,
			Value:  value,
			Column: concentrateformula.FieldCost,
		})
	}
	if value, ok := cfu.mutation.TenantId(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeInt64,
			Value:  value,
			Column: concentrateformula.FieldTenantId,
		})
	}
	if value, ok := cfu.mutation.AddedTenantId(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeInt64,
			Value:  value,
			Column: concentrateformula.FieldTenantId,
		})
	}
	if value, ok := cfu.mutation.TenantName(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: concentrateformula.FieldTenantName,
		})
	}
	if value, ok := cfu.mutation.Remarks(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: concentrateformula.FieldRemarks,
		})
	}
	if value, ok := cfu.mutation.CreatedAt(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeInt64,
			Value:  value,
			Column: concentrateformula.FieldCreatedAt,
		})
	}
	if value, ok := cfu.mutation.AddedCreatedAt(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeInt64,
			Value:  value,
			Column: concentrateformula.FieldCreatedAt,
		})
	}
	if value, ok := cfu.mutation.UpdatedAt(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeInt64,
			Value:  value,
			Column: concentrateformula.FieldUpdatedAt,
		})
	}
	if value, ok := cfu.mutation.AddedUpdatedAt(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeInt64,
			Value:  value,
			Column: concentrateformula.FieldUpdatedAt,
		})
	}
	if value, ok := cfu.mutation.Deleted(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: concentrateformula.FieldDeleted,
		})
	}
	if value, ok := cfu.mutation.AddedDeleted(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: concentrateformula.FieldDeleted,
		})
	}
	if n, err = sqlgraph.UpdateNodes(ctx, cfu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{concentrateformula.Label}
		} else if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return 0, err
	}
	return n, nil
}

// ConcentrateFormulaUpdateOne is the builder for updating a single ConcentrateFormula entity.
type ConcentrateFormulaUpdateOne struct {
	config
	hooks    []Hook
	mutation *ConcentrateFormulaMutation
}

// SetName sets the name field.
func (cfuo *ConcentrateFormulaUpdateOne) SetName(s string) *ConcentrateFormulaUpdateOne {
	cfuo.mutation.SetName(s)
	return cfuo
}

// SetCode sets the code field.
func (cfuo *ConcentrateFormulaUpdateOne) SetCode(s string) *ConcentrateFormulaUpdateOne {
	cfuo.mutation.SetCode(s)
	return cfuo
}

// SetStatus sets the status field.
func (cfuo *ConcentrateFormulaUpdateOne) SetStatus(i int) *ConcentrateFormulaUpdateOne {
	cfuo.mutation.ResetStatus()
	cfuo.mutation.SetStatus(i)
	return cfuo
}

// AddStatus adds i to status.
func (cfuo *ConcentrateFormulaUpdateOne) AddStatus(i int) *ConcentrateFormulaUpdateOne {
	cfuo.mutation.AddStatus(i)
	return cfuo
}

// SetCreateDate sets the createDate field.
func (cfuo *ConcentrateFormulaUpdateOne) SetCreateDate(i int64) *ConcentrateFormulaUpdateOne {
	cfuo.mutation.ResetCreateDate()
	cfuo.mutation.SetCreateDate(i)
	return cfuo
}

// AddCreateDate adds i to createDate.
func (cfuo *ConcentrateFormulaUpdateOne) AddCreateDate(i int64) *ConcentrateFormulaUpdateOne {
	cfuo.mutation.AddCreateDate(i)
	return cfuo
}

// SetAdjustDate sets the adjustDate field.
func (cfuo *ConcentrateFormulaUpdateOne) SetAdjustDate(i int64) *ConcentrateFormulaUpdateOne {
	cfuo.mutation.ResetAdjustDate()
	cfuo.mutation.SetAdjustDate(i)
	return cfuo
}

// AddAdjustDate adds i to adjustDate.
func (cfuo *ConcentrateFormulaUpdateOne) AddAdjustDate(i int64) *ConcentrateFormulaUpdateOne {
	cfuo.mutation.AddAdjustDate(i)
	return cfuo
}

// SetDisableDate sets the disableDate field.
func (cfuo *ConcentrateFormulaUpdateOne) SetDisableDate(i int64) *ConcentrateFormulaUpdateOne {
	cfuo.mutation.ResetDisableDate()
	cfuo.mutation.SetDisableDate(i)
	return cfuo
}

// AddDisableDate adds i to disableDate.
func (cfuo *ConcentrateFormulaUpdateOne) AddDisableDate(i int64) *ConcentrateFormulaUpdateOne {
	cfuo.mutation.AddDisableDate(i)
	return cfuo
}

// SetCost sets the cost field.
func (cfuo *ConcentrateFormulaUpdateOne) SetCost(i int64) *ConcentrateFormulaUpdateOne {
	cfuo.mutation.ResetCost()
	cfuo.mutation.SetCost(i)
	return cfuo
}

// AddCost adds i to cost.
func (cfuo *ConcentrateFormulaUpdateOne) AddCost(i int64) *ConcentrateFormulaUpdateOne {
	cfuo.mutation.AddCost(i)
	return cfuo
}

// SetTenantId sets the tenantId field.
func (cfuo *ConcentrateFormulaUpdateOne) SetTenantId(i int64) *ConcentrateFormulaUpdateOne {
	cfuo.mutation.ResetTenantId()
	cfuo.mutation.SetTenantId(i)
	return cfuo
}

// AddTenantId adds i to tenantId.
func (cfuo *ConcentrateFormulaUpdateOne) AddTenantId(i int64) *ConcentrateFormulaUpdateOne {
	cfuo.mutation.AddTenantId(i)
	return cfuo
}

// SetTenantName sets the tenantName field.
func (cfuo *ConcentrateFormulaUpdateOne) SetTenantName(s string) *ConcentrateFormulaUpdateOne {
	cfuo.mutation.SetTenantName(s)
	return cfuo
}

// SetRemarks sets the remarks field.
func (cfuo *ConcentrateFormulaUpdateOne) SetRemarks(s string) *ConcentrateFormulaUpdateOne {
	cfuo.mutation.SetRemarks(s)
	return cfuo
}

// SetCreatedAt sets the createdAt field.
func (cfuo *ConcentrateFormulaUpdateOne) SetCreatedAt(i int64) *ConcentrateFormulaUpdateOne {
	cfuo.mutation.ResetCreatedAt()
	cfuo.mutation.SetCreatedAt(i)
	return cfuo
}

// AddCreatedAt adds i to createdAt.
func (cfuo *ConcentrateFormulaUpdateOne) AddCreatedAt(i int64) *ConcentrateFormulaUpdateOne {
	cfuo.mutation.AddCreatedAt(i)
	return cfuo
}

// SetUpdatedAt sets the updatedAt field.
func (cfuo *ConcentrateFormulaUpdateOne) SetUpdatedAt(i int64) *ConcentrateFormulaUpdateOne {
	cfuo.mutation.ResetUpdatedAt()
	cfuo.mutation.SetUpdatedAt(i)
	return cfuo
}

// AddUpdatedAt adds i to updatedAt.
func (cfuo *ConcentrateFormulaUpdateOne) AddUpdatedAt(i int64) *ConcentrateFormulaUpdateOne {
	cfuo.mutation.AddUpdatedAt(i)
	return cfuo
}

// SetDeleted sets the deleted field.
func (cfuo *ConcentrateFormulaUpdateOne) SetDeleted(i int) *ConcentrateFormulaUpdateOne {
	cfuo.mutation.ResetDeleted()
	cfuo.mutation.SetDeleted(i)
	return cfuo
}

// AddDeleted adds i to deleted.
func (cfuo *ConcentrateFormulaUpdateOne) AddDeleted(i int) *ConcentrateFormulaUpdateOne {
	cfuo.mutation.AddDeleted(i)
	return cfuo
}

// Mutation returns the ConcentrateFormulaMutation object of the builder.
func (cfuo *ConcentrateFormulaUpdateOne) Mutation() *ConcentrateFormulaMutation {
	return cfuo.mutation
}

// Save executes the query and returns the updated entity.
func (cfuo *ConcentrateFormulaUpdateOne) Save(ctx context.Context) (*ConcentrateFormula, error) {
	var (
		err  error
		node *ConcentrateFormula
	)
	if len(cfuo.hooks) == 0 {
		node, err = cfuo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*ConcentrateFormulaMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			cfuo.mutation = mutation
			node, err = cfuo.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(cfuo.hooks) - 1; i >= 0; i-- {
			mut = cfuo.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, cfuo.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (cfuo *ConcentrateFormulaUpdateOne) SaveX(ctx context.Context) *ConcentrateFormula {
	node, err := cfuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (cfuo *ConcentrateFormulaUpdateOne) Exec(ctx context.Context) error {
	_, err := cfuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (cfuo *ConcentrateFormulaUpdateOne) ExecX(ctx context.Context) {
	if err := cfuo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (cfuo *ConcentrateFormulaUpdateOne) sqlSave(ctx context.Context) (_node *ConcentrateFormula, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   concentrateformula.Table,
			Columns: concentrateformula.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt64,
				Column: concentrateformula.FieldID,
			},
		},
	}
	id, ok := cfuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "ID", err: fmt.Errorf("missing ConcentrateFormula.ID for update")}
	}
	_spec.Node.ID.Value = id
	if value, ok := cfuo.mutation.Name(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: concentrateformula.FieldName,
		})
	}
	if value, ok := cfuo.mutation.Code(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: concentrateformula.FieldCode,
		})
	}
	if value, ok := cfuo.mutation.Status(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: concentrateformula.FieldStatus,
		})
	}
	if value, ok := cfuo.mutation.AddedStatus(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: concentrateformula.FieldStatus,
		})
	}
	if value, ok := cfuo.mutation.CreateDate(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeInt64,
			Value:  value,
			Column: concentrateformula.FieldCreateDate,
		})
	}
	if value, ok := cfuo.mutation.AddedCreateDate(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeInt64,
			Value:  value,
			Column: concentrateformula.FieldCreateDate,
		})
	}
	if value, ok := cfuo.mutation.AdjustDate(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeInt64,
			Value:  value,
			Column: concentrateformula.FieldAdjustDate,
		})
	}
	if value, ok := cfuo.mutation.AddedAdjustDate(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeInt64,
			Value:  value,
			Column: concentrateformula.FieldAdjustDate,
		})
	}
	if value, ok := cfuo.mutation.DisableDate(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeInt64,
			Value:  value,
			Column: concentrateformula.FieldDisableDate,
		})
	}
	if value, ok := cfuo.mutation.AddedDisableDate(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeInt64,
			Value:  value,
			Column: concentrateformula.FieldDisableDate,
		})
	}
	if value, ok := cfuo.mutation.Cost(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeInt64,
			Value:  value,
			Column: concentrateformula.FieldCost,
		})
	}
	if value, ok := cfuo.mutation.AddedCost(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeInt64,
			Value:  value,
			Column: concentrateformula.FieldCost,
		})
	}
	if value, ok := cfuo.mutation.TenantId(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeInt64,
			Value:  value,
			Column: concentrateformula.FieldTenantId,
		})
	}
	if value, ok := cfuo.mutation.AddedTenantId(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeInt64,
			Value:  value,
			Column: concentrateformula.FieldTenantId,
		})
	}
	if value, ok := cfuo.mutation.TenantName(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: concentrateformula.FieldTenantName,
		})
	}
	if value, ok := cfuo.mutation.Remarks(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: concentrateformula.FieldRemarks,
		})
	}
	if value, ok := cfuo.mutation.CreatedAt(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeInt64,
			Value:  value,
			Column: concentrateformula.FieldCreatedAt,
		})
	}
	if value, ok := cfuo.mutation.AddedCreatedAt(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeInt64,
			Value:  value,
			Column: concentrateformula.FieldCreatedAt,
		})
	}
	if value, ok := cfuo.mutation.UpdatedAt(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeInt64,
			Value:  value,
			Column: concentrateformula.FieldUpdatedAt,
		})
	}
	if value, ok := cfuo.mutation.AddedUpdatedAt(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeInt64,
			Value:  value,
			Column: concentrateformula.FieldUpdatedAt,
		})
	}
	if value, ok := cfuo.mutation.Deleted(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: concentrateformula.FieldDeleted,
		})
	}
	if value, ok := cfuo.mutation.AddedDeleted(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: concentrateformula.FieldDeleted,
		})
	}
	_node = &ConcentrateFormula{config: cfuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues()
	if err = sqlgraph.UpdateNode(ctx, cfuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{concentrateformula.Label}
		} else if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return nil, err
	}
	return _node, nil
}
