// Code generated by entc, DO NOT EDIT.

package ent

import (
	"cattleai/ent/epidemictype"
	"context"
	"errors"
	"fmt"

	"github.com/facebook/ent/dialect/sql/sqlgraph"
	"github.com/facebook/ent/schema/field"
)

// EpidemicTypeCreate is the builder for creating a EpidemicType entity.
type EpidemicTypeCreate struct {
	config
	mutation *EpidemicTypeMutation
	hooks    []Hook
}

// SetName sets the name field.
func (etc *EpidemicTypeCreate) SetName(s string) *EpidemicTypeCreate {
	etc.mutation.SetName(s)
	return etc
}

// Mutation returns the EpidemicTypeMutation object of the builder.
func (etc *EpidemicTypeCreate) Mutation() *EpidemicTypeMutation {
	return etc.mutation
}

// Save creates the EpidemicType in the database.
func (etc *EpidemicTypeCreate) Save(ctx context.Context) (*EpidemicType, error) {
	var (
		err  error
		node *EpidemicType
	)
	if len(etc.hooks) == 0 {
		if err = etc.check(); err != nil {
			return nil, err
		}
		node, err = etc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*EpidemicTypeMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = etc.check(); err != nil {
				return nil, err
			}
			etc.mutation = mutation
			node, err = etc.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(etc.hooks) - 1; i >= 0; i-- {
			mut = etc.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, etc.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (etc *EpidemicTypeCreate) SaveX(ctx context.Context) *EpidemicType {
	v, err := etc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// check runs all checks and user-defined validators on the builder.
func (etc *EpidemicTypeCreate) check() error {
	if _, ok := etc.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New("ent: missing required field \"name\"")}
	}
	if v, ok := etc.mutation.Name(); ok {
		if err := epidemictype.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf("ent: validator failed for field \"name\": %w", err)}
		}
	}
	return nil
}

func (etc *EpidemicTypeCreate) sqlSave(ctx context.Context) (*EpidemicType, error) {
	_node, _spec := etc.createSpec()
	if err := sqlgraph.CreateNode(ctx, etc.driver, _spec); err != nil {
		if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	return _node, nil
}

func (etc *EpidemicTypeCreate) createSpec() (*EpidemicType, *sqlgraph.CreateSpec) {
	var (
		_node = &EpidemicType{config: etc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: epidemictype.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt64,
				Column: epidemictype.FieldID,
			},
		}
	)
	if value, ok := etc.mutation.Name(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: epidemictype.FieldName,
		})
		_node.Name = value
	}
	return _node, _spec
}

// EpidemicTypeCreateBulk is the builder for creating a bulk of EpidemicType entities.
type EpidemicTypeCreateBulk struct {
	config
	builders []*EpidemicTypeCreate
}

// Save creates the EpidemicType entities in the database.
func (etcb *EpidemicTypeCreateBulk) Save(ctx context.Context) ([]*EpidemicType, error) {
	specs := make([]*sqlgraph.CreateSpec, len(etcb.builders))
	nodes := make([]*EpidemicType, len(etcb.builders))
	mutators := make([]Mutator, len(etcb.builders))
	for i := range etcb.builders {
		func(i int, root context.Context) {
			builder := etcb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*EpidemicTypeMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, etcb.builders[i+1].mutation)
				} else {
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, etcb.driver, &sqlgraph.BatchCreateSpec{Nodes: specs}); err != nil {
						if cerr, ok := isSQLConstraintError(err); ok {
							err = cerr
						}
					}
				}
				mutation.done = true
				if err != nil {
					return nil, err
				}
				id := specs[i].ID.Value.(int64)
				nodes[i].ID = int64(id)
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, etcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX calls Save and panics if Save returns an error.
func (etcb *EpidemicTypeCreateBulk) SaveX(ctx context.Context) []*EpidemicType {
	v, err := etcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}
