// Code generated by entc, DO NOT EDIT.

package ent

import (
	"cattleai/ent/estrus"
	"context"
	"errors"
	"fmt"

	"github.com/facebook/ent/dialect/sql/sqlgraph"
	"github.com/facebook/ent/schema/field"
)

// EstrusCreate is the builder for creating a Estrus entity.
type EstrusCreate struct {
	config
	mutation *EstrusMutation
	hooks    []Hook
}

// SetName sets the name field.
func (ec *EstrusCreate) SetName(s string) *EstrusCreate {
	ec.mutation.SetName(s)
	return ec
}

// SetNillableName sets the name field if the given value is not nil.
func (ec *EstrusCreate) SetNillableName(s *string) *EstrusCreate {
	if s != nil {
		ec.SetName(*s)
	}
	return ec
}

// SetEarNumber sets the earNumber field.
func (ec *EstrusCreate) SetEarNumber(s string) *EstrusCreate {
	ec.mutation.SetEarNumber(s)
	return ec
}

// SetTimes sets the times field.
func (ec *EstrusCreate) SetTimes(i int) *EstrusCreate {
	ec.mutation.SetTimes(i)
	return ec
}

// SetReproductiveState sets the reproductiveState field.
func (ec *EstrusCreate) SetReproductiveState(s string) *EstrusCreate {
	ec.mutation.SetReproductiveState(s)
	return ec
}

// SetShedName sets the shedName field.
func (ec *EstrusCreate) SetShedName(s string) *EstrusCreate {
	ec.mutation.SetShedName(s)
	return ec
}

// SetEstrusAt sets the estrusAt field.
func (ec *EstrusCreate) SetEstrusAt(i int64) *EstrusCreate {
	ec.mutation.SetEstrusAt(i)
	return ec
}

// SetEstrusTypeId sets the estrusTypeId field.
func (ec *EstrusCreate) SetEstrusTypeId(i int) *EstrusCreate {
	ec.mutation.SetEstrusTypeId(i)
	return ec
}

// SetEstrusTypeName sets the estrusTypeName field.
func (ec *EstrusCreate) SetEstrusTypeName(s string) *EstrusCreate {
	ec.mutation.SetEstrusTypeName(s)
	return ec
}

// SetUserName sets the userName field.
func (ec *EstrusCreate) SetUserName(s string) *EstrusCreate {
	ec.mutation.SetUserName(s)
	return ec
}

// SetRemarks sets the remarks field.
func (ec *EstrusCreate) SetRemarks(s string) *EstrusCreate {
	ec.mutation.SetRemarks(s)
	return ec
}

// SetCreatedAt sets the createdAt field.
func (ec *EstrusCreate) SetCreatedAt(i int64) *EstrusCreate {
	ec.mutation.SetCreatedAt(i)
	return ec
}

// SetUpdatedAt sets the updatedAt field.
func (ec *EstrusCreate) SetUpdatedAt(i int64) *EstrusCreate {
	ec.mutation.SetUpdatedAt(i)
	return ec
}

// SetDeleted sets the deleted field.
func (ec *EstrusCreate) SetDeleted(i int) *EstrusCreate {
	ec.mutation.SetDeleted(i)
	return ec
}

// Mutation returns the EstrusMutation object of the builder.
func (ec *EstrusCreate) Mutation() *EstrusMutation {
	return ec.mutation
}

// Save creates the Estrus in the database.
func (ec *EstrusCreate) Save(ctx context.Context) (*Estrus, error) {
	var (
		err  error
		node *Estrus
	)
	if len(ec.hooks) == 0 {
		if err = ec.check(); err != nil {
			return nil, err
		}
		node, err = ec.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*EstrusMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = ec.check(); err != nil {
				return nil, err
			}
			ec.mutation = mutation
			node, err = ec.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(ec.hooks) - 1; i >= 0; i-- {
			mut = ec.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, ec.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (ec *EstrusCreate) SaveX(ctx context.Context) *Estrus {
	v, err := ec.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// check runs all checks and user-defined validators on the builder.
func (ec *EstrusCreate) check() error {
	if _, ok := ec.mutation.EarNumber(); !ok {
		return &ValidationError{Name: "earNumber", err: errors.New("ent: missing required field \"earNumber\"")}
	}
	if _, ok := ec.mutation.Times(); !ok {
		return &ValidationError{Name: "times", err: errors.New("ent: missing required field \"times\"")}
	}
	if _, ok := ec.mutation.ReproductiveState(); !ok {
		return &ValidationError{Name: "reproductiveState", err: errors.New("ent: missing required field \"reproductiveState\"")}
	}
	if _, ok := ec.mutation.ShedName(); !ok {
		return &ValidationError{Name: "shedName", err: errors.New("ent: missing required field \"shedName\"")}
	}
	if _, ok := ec.mutation.EstrusAt(); !ok {
		return &ValidationError{Name: "estrusAt", err: errors.New("ent: missing required field \"estrusAt\"")}
	}
	if _, ok := ec.mutation.EstrusTypeId(); !ok {
		return &ValidationError{Name: "estrusTypeId", err: errors.New("ent: missing required field \"estrusTypeId\"")}
	}
	if _, ok := ec.mutation.EstrusTypeName(); !ok {
		return &ValidationError{Name: "estrusTypeName", err: errors.New("ent: missing required field \"estrusTypeName\"")}
	}
	if _, ok := ec.mutation.UserName(); !ok {
		return &ValidationError{Name: "userName", err: errors.New("ent: missing required field \"userName\"")}
	}
	if _, ok := ec.mutation.Remarks(); !ok {
		return &ValidationError{Name: "remarks", err: errors.New("ent: missing required field \"remarks\"")}
	}
	if _, ok := ec.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "createdAt", err: errors.New("ent: missing required field \"createdAt\"")}
	}
	if _, ok := ec.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updatedAt", err: errors.New("ent: missing required field \"updatedAt\"")}
	}
	if _, ok := ec.mutation.Deleted(); !ok {
		return &ValidationError{Name: "deleted", err: errors.New("ent: missing required field \"deleted\"")}
	}
	return nil
}

func (ec *EstrusCreate) sqlSave(ctx context.Context) (*Estrus, error) {
	_node, _spec := ec.createSpec()
	if err := sqlgraph.CreateNode(ctx, ec.driver, _spec); err != nil {
		if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	return _node, nil
}

func (ec *EstrusCreate) createSpec() (*Estrus, *sqlgraph.CreateSpec) {
	var (
		_node = &Estrus{config: ec.config}
		_spec = &sqlgraph.CreateSpec{
			Table: estrus.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt64,
				Column: estrus.FieldID,
			},
		}
	)
	if value, ok := ec.mutation.Name(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: estrus.FieldName,
		})
		_node.Name = value
	}
	if value, ok := ec.mutation.EarNumber(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: estrus.FieldEarNumber,
		})
		_node.EarNumber = value
	}
	if value, ok := ec.mutation.Times(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: estrus.FieldTimes,
		})
		_node.Times = value
	}
	if value, ok := ec.mutation.ReproductiveState(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: estrus.FieldReproductiveState,
		})
		_node.ReproductiveState = value
	}
	if value, ok := ec.mutation.ShedName(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: estrus.FieldShedName,
		})
		_node.ShedName = value
	}
	if value, ok := ec.mutation.EstrusAt(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeInt64,
			Value:  value,
			Column: estrus.FieldEstrusAt,
		})
		_node.EstrusAt = value
	}
	if value, ok := ec.mutation.EstrusTypeId(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: estrus.FieldEstrusTypeId,
		})
		_node.EstrusTypeId = value
	}
	if value, ok := ec.mutation.EstrusTypeName(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: estrus.FieldEstrusTypeName,
		})
		_node.EstrusTypeName = value
	}
	if value, ok := ec.mutation.UserName(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: estrus.FieldUserName,
		})
		_node.UserName = value
	}
	if value, ok := ec.mutation.Remarks(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: estrus.FieldRemarks,
		})
		_node.Remarks = value
	}
	if value, ok := ec.mutation.CreatedAt(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeInt64,
			Value:  value,
			Column: estrus.FieldCreatedAt,
		})
		_node.CreatedAt = value
	}
	if value, ok := ec.mutation.UpdatedAt(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeInt64,
			Value:  value,
			Column: estrus.FieldUpdatedAt,
		})
		_node.UpdatedAt = value
	}
	if value, ok := ec.mutation.Deleted(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: estrus.FieldDeleted,
		})
		_node.Deleted = value
	}
	return _node, _spec
}

// EstrusCreateBulk is the builder for creating a bulk of Estrus entities.
type EstrusCreateBulk struct {
	config
	builders []*EstrusCreate
}

// Save creates the Estrus entities in the database.
func (ecb *EstrusCreateBulk) Save(ctx context.Context) ([]*Estrus, error) {
	specs := make([]*sqlgraph.CreateSpec, len(ecb.builders))
	nodes := make([]*Estrus, len(ecb.builders))
	mutators := make([]Mutator, len(ecb.builders))
	for i := range ecb.builders {
		func(i int, root context.Context) {
			builder := ecb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*EstrusMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, ecb.builders[i+1].mutation)
				} else {
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, ecb.driver, &sqlgraph.BatchCreateSpec{Nodes: specs}); err != nil {
						if cerr, ok := isSQLConstraintError(err); ok {
							err = cerr
						}
					}
				}
				mutation.done = true
				if err != nil {
					return nil, err
				}
				id := specs[i].ID.Value.(int64)
				nodes[i].ID = int64(id)
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, ecb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX calls Save and panics if Save returns an error.
func (ecb *EstrusCreateBulk) SaveX(ctx context.Context) []*Estrus {
	v, err := ecb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}
