// Code generated by ent, DO NOT EDIT.

package ent

import (
	"cattleai/ent/estrustype"
	"fmt"
	"strings"

	"entgo.io/ent/dialect/sql"
)

// EstrusType is the model entity for the EstrusType schema.
type EstrusType struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// 名称
	Name string `json:"name,omitempty"`
}

// scanValues returns the types for scanning values from sql.Rows.
func (*EstrusType) scanValues(columns []string) ([]interface{}, error) {
	values := make([]interface{}, len(columns))
	for i := range columns {
		switch columns[i] {
		case estrustype.FieldID:
			values[i] = new(sql.NullInt64)
		case estrustype.FieldName:
			values[i] = new(sql.NullString)
		default:
			return nil, fmt.Errorf("unexpected column %q for type EstrusType", columns[i])
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the EstrusType fields.
func (et *EstrusType) assignValues(columns []string, values []interface{}) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case estrustype.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			et.ID = int(value.Int64)
		case estrustype.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				et.Name = value.String
			}
		}
	}
	return nil
}

// Update returns a builder for updating this EstrusType.
// Note that you need to call EstrusType.Unwrap() before calling this method if this EstrusType
// was returned from a transaction, and the transaction was committed or rolled back.
func (et *EstrusType) Update() *EstrusTypeUpdateOne {
	return (&EstrusTypeClient{config: et.config}).UpdateOne(et)
}

// Unwrap unwraps the EstrusType entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (et *EstrusType) Unwrap() *EstrusType {
	_tx, ok := et.config.driver.(*txDriver)
	if !ok {
		panic("ent: EstrusType is not a transactional entity")
	}
	et.config.driver = _tx.drv
	return et
}

// String implements the fmt.Stringer.
func (et *EstrusType) String() string {
	var builder strings.Builder
	builder.WriteString("EstrusType(")
	builder.WriteString(fmt.Sprintf("id=%v, ", et.ID))
	builder.WriteString("name=")
	builder.WriteString(et.Name)
	builder.WriteByte(')')
	return builder.String()
}

// EstrusTypes is a parsable slice of EstrusType.
type EstrusTypes []*EstrusType

func (et EstrusTypes) config(cfg config) {
	for _i := range et {
		et[_i].config = cfg
	}
}
