// Code generated by ent, DO NOT EDIT.

package ent

import (
	"cattleai/ent/predicate"
	"cattleai/ent/pregnancytestmethod"
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// PregnancyTestMethodUpdate is the builder for updating PregnancyTestMethod entities.
type PregnancyTestMethodUpdate struct {
	config
	hooks    []Hook
	mutation *PregnancyTestMethodMutation
}

// Where appends a list predicates to the PregnancyTestMethodUpdate builder.
func (ptmu *PregnancyTestMethodUpdate) Where(ps ...predicate.PregnancyTestMethod) *PregnancyTestMethodUpdate {
	ptmu.mutation.Where(ps...)
	return ptmu
}

// SetName sets the "name" field.
func (ptmu *PregnancyTestMethodUpdate) SetName(s string) *PregnancyTestMethodUpdate {
	ptmu.mutation.SetName(s)
	return ptmu
}

// Mutation returns the PregnancyTestMethodMutation object of the builder.
func (ptmu *PregnancyTestMethodUpdate) Mutation() *PregnancyTestMethodMutation {
	return ptmu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (ptmu *PregnancyTestMethodUpdate) Save(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(ptmu.hooks) == 0 {
		if err = ptmu.check(); err != nil {
			return 0, err
		}
		affected, err = ptmu.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*PregnancyTestMethodMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = ptmu.check(); err != nil {
				return 0, err
			}
			ptmu.mutation = mutation
			affected, err = ptmu.sqlSave(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(ptmu.hooks) - 1; i >= 0; i-- {
			if ptmu.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = ptmu.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, ptmu.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (ptmu *PregnancyTestMethodUpdate) SaveX(ctx context.Context) int {
	affected, err := ptmu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (ptmu *PregnancyTestMethodUpdate) Exec(ctx context.Context) error {
	_, err := ptmu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ptmu *PregnancyTestMethodUpdate) ExecX(ctx context.Context) {
	if err := ptmu.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (ptmu *PregnancyTestMethodUpdate) check() error {
	if v, ok := ptmu.mutation.Name(); ok {
		if err := pregnancytestmethod.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "PregnancyTestMethod.name": %w`, err)}
		}
	}
	return nil
}

func (ptmu *PregnancyTestMethodUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   pregnancytestmethod.Table,
			Columns: pregnancytestmethod.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: pregnancytestmethod.FieldID,
			},
		},
	}
	if ps := ptmu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := ptmu.mutation.Name(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: pregnancytestmethod.FieldName,
		})
	}
	if n, err = sqlgraph.UpdateNodes(ctx, ptmu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{pregnancytestmethod.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	return n, nil
}

// PregnancyTestMethodUpdateOne is the builder for updating a single PregnancyTestMethod entity.
type PregnancyTestMethodUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *PregnancyTestMethodMutation
}

// SetName sets the "name" field.
func (ptmuo *PregnancyTestMethodUpdateOne) SetName(s string) *PregnancyTestMethodUpdateOne {
	ptmuo.mutation.SetName(s)
	return ptmuo
}

// Mutation returns the PregnancyTestMethodMutation object of the builder.
func (ptmuo *PregnancyTestMethodUpdateOne) Mutation() *PregnancyTestMethodMutation {
	return ptmuo.mutation
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (ptmuo *PregnancyTestMethodUpdateOne) Select(field string, fields ...string) *PregnancyTestMethodUpdateOne {
	ptmuo.fields = append([]string{field}, fields...)
	return ptmuo
}

// Save executes the query and returns the updated PregnancyTestMethod entity.
func (ptmuo *PregnancyTestMethodUpdateOne) Save(ctx context.Context) (*PregnancyTestMethod, error) {
	var (
		err  error
		node *PregnancyTestMethod
	)
	if len(ptmuo.hooks) == 0 {
		if err = ptmuo.check(); err != nil {
			return nil, err
		}
		node, err = ptmuo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*PregnancyTestMethodMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = ptmuo.check(); err != nil {
				return nil, err
			}
			ptmuo.mutation = mutation
			node, err = ptmuo.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(ptmuo.hooks) - 1; i >= 0; i-- {
			if ptmuo.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = ptmuo.hooks[i](mut)
		}
		v, err := mut.Mutate(ctx, ptmuo.mutation)
		if err != nil {
			return nil, err
		}
		nv, ok := v.(*PregnancyTestMethod)
		if !ok {
			return nil, fmt.Errorf("unexpected node type %T returned from PregnancyTestMethodMutation", v)
		}
		node = nv
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (ptmuo *PregnancyTestMethodUpdateOne) SaveX(ctx context.Context) *PregnancyTestMethod {
	node, err := ptmuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (ptmuo *PregnancyTestMethodUpdateOne) Exec(ctx context.Context) error {
	_, err := ptmuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ptmuo *PregnancyTestMethodUpdateOne) ExecX(ctx context.Context) {
	if err := ptmuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (ptmuo *PregnancyTestMethodUpdateOne) check() error {
	if v, ok := ptmuo.mutation.Name(); ok {
		if err := pregnancytestmethod.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "PregnancyTestMethod.name": %w`, err)}
		}
	}
	return nil
}

func (ptmuo *PregnancyTestMethodUpdateOne) sqlSave(ctx context.Context) (_node *PregnancyTestMethod, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   pregnancytestmethod.Table,
			Columns: pregnancytestmethod.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: pregnancytestmethod.FieldID,
			},
		},
	}
	id, ok := ptmuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "PregnancyTestMethod.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := ptmuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, pregnancytestmethod.FieldID)
		for _, f := range fields {
			if !pregnancytestmethod.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != pregnancytestmethod.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := ptmuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := ptmuo.mutation.Name(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: pregnancytestmethod.FieldName,
		})
	}
	_node = &PregnancyTestMethod{config: ptmuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, ptmuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{pregnancytestmethod.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	return _node, nil
}
