// Code generated by ent, DO NOT EDIT.

package ent

import (
	"cattleai/ent/predicate"
	"cattleai/ent/pregnancytestresult"
	"context"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// PregnancyTestResultQuery is the builder for querying PregnancyTestResult entities.
type PregnancyTestResultQuery struct {
	config
	limit      *int
	offset     *int
	unique     *bool
	order      []OrderFunc
	fields     []string
	predicates []predicate.PregnancyTestResult
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the PregnancyTestResultQuery builder.
func (ptrq *PregnancyTestResultQuery) Where(ps ...predicate.PregnancyTestResult) *PregnancyTestResultQuery {
	ptrq.predicates = append(ptrq.predicates, ps...)
	return ptrq
}

// Limit adds a limit step to the query.
func (ptrq *PregnancyTestResultQuery) Limit(limit int) *PregnancyTestResultQuery {
	ptrq.limit = &limit
	return ptrq
}

// Offset adds an offset step to the query.
func (ptrq *PregnancyTestResultQuery) Offset(offset int) *PregnancyTestResultQuery {
	ptrq.offset = &offset
	return ptrq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (ptrq *PregnancyTestResultQuery) Unique(unique bool) *PregnancyTestResultQuery {
	ptrq.unique = &unique
	return ptrq
}

// Order adds an order step to the query.
func (ptrq *PregnancyTestResultQuery) Order(o ...OrderFunc) *PregnancyTestResultQuery {
	ptrq.order = append(ptrq.order, o...)
	return ptrq
}

// First returns the first PregnancyTestResult entity from the query.
// Returns a *NotFoundError when no PregnancyTestResult was found.
func (ptrq *PregnancyTestResultQuery) First(ctx context.Context) (*PregnancyTestResult, error) {
	nodes, err := ptrq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{pregnancytestresult.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (ptrq *PregnancyTestResultQuery) FirstX(ctx context.Context) *PregnancyTestResult {
	node, err := ptrq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first PregnancyTestResult ID from the query.
// Returns a *NotFoundError when no PregnancyTestResult ID was found.
func (ptrq *PregnancyTestResultQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = ptrq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{pregnancytestresult.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (ptrq *PregnancyTestResultQuery) FirstIDX(ctx context.Context) int {
	id, err := ptrq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single PregnancyTestResult entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one PregnancyTestResult entity is found.
// Returns a *NotFoundError when no PregnancyTestResult entities are found.
func (ptrq *PregnancyTestResultQuery) Only(ctx context.Context) (*PregnancyTestResult, error) {
	nodes, err := ptrq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{pregnancytestresult.Label}
	default:
		return nil, &NotSingularError{pregnancytestresult.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (ptrq *PregnancyTestResultQuery) OnlyX(ctx context.Context) *PregnancyTestResult {
	node, err := ptrq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only PregnancyTestResult ID in the query.
// Returns a *NotSingularError when more than one PregnancyTestResult ID is found.
// Returns a *NotFoundError when no entities are found.
func (ptrq *PregnancyTestResultQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = ptrq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{pregnancytestresult.Label}
	default:
		err = &NotSingularError{pregnancytestresult.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (ptrq *PregnancyTestResultQuery) OnlyIDX(ctx context.Context) int {
	id, err := ptrq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of PregnancyTestResults.
func (ptrq *PregnancyTestResultQuery) All(ctx context.Context) ([]*PregnancyTestResult, error) {
	if err := ptrq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return ptrq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (ptrq *PregnancyTestResultQuery) AllX(ctx context.Context) []*PregnancyTestResult {
	nodes, err := ptrq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of PregnancyTestResult IDs.
func (ptrq *PregnancyTestResultQuery) IDs(ctx context.Context) ([]int, error) {
	var ids []int
	if err := ptrq.Select(pregnancytestresult.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (ptrq *PregnancyTestResultQuery) IDsX(ctx context.Context) []int {
	ids, err := ptrq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (ptrq *PregnancyTestResultQuery) Count(ctx context.Context) (int, error) {
	if err := ptrq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return ptrq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (ptrq *PregnancyTestResultQuery) CountX(ctx context.Context) int {
	count, err := ptrq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (ptrq *PregnancyTestResultQuery) Exist(ctx context.Context) (bool, error) {
	if err := ptrq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return ptrq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (ptrq *PregnancyTestResultQuery) ExistX(ctx context.Context) bool {
	exist, err := ptrq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the PregnancyTestResultQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (ptrq *PregnancyTestResultQuery) Clone() *PregnancyTestResultQuery {
	if ptrq == nil {
		return nil
	}
	return &PregnancyTestResultQuery{
		config:     ptrq.config,
		limit:      ptrq.limit,
		offset:     ptrq.offset,
		order:      append([]OrderFunc{}, ptrq.order...),
		predicates: append([]predicate.PregnancyTestResult{}, ptrq.predicates...),
		// clone intermediate query.
		sql:    ptrq.sql.Clone(),
		path:   ptrq.path,
		unique: ptrq.unique,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Name string `json:"name,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.PregnancyTestResult.Query().
//		GroupBy(pregnancytestresult.FieldName).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (ptrq *PregnancyTestResultQuery) GroupBy(field string, fields ...string) *PregnancyTestResultGroupBy {
	grbuild := &PregnancyTestResultGroupBy{config: ptrq.config}
	grbuild.fields = append([]string{field}, fields...)
	grbuild.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := ptrq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return ptrq.sqlQuery(ctx), nil
	}
	grbuild.label = pregnancytestresult.Label
	grbuild.flds, grbuild.scan = &grbuild.fields, grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Name string `json:"name,omitempty"`
//	}
//
//	client.PregnancyTestResult.Query().
//		Select(pregnancytestresult.FieldName).
//		Scan(ctx, &v)
func (ptrq *PregnancyTestResultQuery) Select(fields ...string) *PregnancyTestResultSelect {
	ptrq.fields = append(ptrq.fields, fields...)
	selbuild := &PregnancyTestResultSelect{PregnancyTestResultQuery: ptrq}
	selbuild.label = pregnancytestresult.Label
	selbuild.flds, selbuild.scan = &ptrq.fields, selbuild.Scan
	return selbuild
}

func (ptrq *PregnancyTestResultQuery) prepareQuery(ctx context.Context) error {
	for _, f := range ptrq.fields {
		if !pregnancytestresult.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if ptrq.path != nil {
		prev, err := ptrq.path(ctx)
		if err != nil {
			return err
		}
		ptrq.sql = prev
	}
	return nil
}

func (ptrq *PregnancyTestResultQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*PregnancyTestResult, error) {
	var (
		nodes = []*PregnancyTestResult{}
		_spec = ptrq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]interface{}, error) {
		return (*PregnancyTestResult).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []interface{}) error {
		node := &PregnancyTestResult{config: ptrq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, ptrq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (ptrq *PregnancyTestResultQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := ptrq.querySpec()
	_spec.Node.Columns = ptrq.fields
	if len(ptrq.fields) > 0 {
		_spec.Unique = ptrq.unique != nil && *ptrq.unique
	}
	return sqlgraph.CountNodes(ctx, ptrq.driver, _spec)
}

func (ptrq *PregnancyTestResultQuery) sqlExist(ctx context.Context) (bool, error) {
	n, err := ptrq.sqlCount(ctx)
	if err != nil {
		return false, fmt.Errorf("ent: check existence: %w", err)
	}
	return n > 0, nil
}

func (ptrq *PregnancyTestResultQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   pregnancytestresult.Table,
			Columns: pregnancytestresult.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: pregnancytestresult.FieldID,
			},
		},
		From:   ptrq.sql,
		Unique: true,
	}
	if unique := ptrq.unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := ptrq.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, pregnancytestresult.FieldID)
		for i := range fields {
			if fields[i] != pregnancytestresult.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := ptrq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := ptrq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := ptrq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := ptrq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (ptrq *PregnancyTestResultQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(ptrq.driver.Dialect())
	t1 := builder.Table(pregnancytestresult.Table)
	columns := ptrq.fields
	if len(columns) == 0 {
		columns = pregnancytestresult.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if ptrq.sql != nil {
		selector = ptrq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if ptrq.unique != nil && *ptrq.unique {
		selector.Distinct()
	}
	for _, p := range ptrq.predicates {
		p(selector)
	}
	for _, p := range ptrq.order {
		p(selector)
	}
	if offset := ptrq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := ptrq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// PregnancyTestResultGroupBy is the group-by builder for PregnancyTestResult entities.
type PregnancyTestResultGroupBy struct {
	config
	selector
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (ptrgb *PregnancyTestResultGroupBy) Aggregate(fns ...AggregateFunc) *PregnancyTestResultGroupBy {
	ptrgb.fns = append(ptrgb.fns, fns...)
	return ptrgb
}

// Scan applies the group-by query and scans the result into the given value.
func (ptrgb *PregnancyTestResultGroupBy) Scan(ctx context.Context, v interface{}) error {
	query, err := ptrgb.path(ctx)
	if err != nil {
		return err
	}
	ptrgb.sql = query
	return ptrgb.sqlScan(ctx, v)
}

func (ptrgb *PregnancyTestResultGroupBy) sqlScan(ctx context.Context, v interface{}) error {
	for _, f := range ptrgb.fields {
		if !pregnancytestresult.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for group-by", f)}
		}
	}
	selector := ptrgb.sqlQuery()
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := ptrgb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (ptrgb *PregnancyTestResultGroupBy) sqlQuery() *sql.Selector {
	selector := ptrgb.sql.Select()
	aggregation := make([]string, 0, len(ptrgb.fns))
	for _, fn := range ptrgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	// If no columns were selected in a custom aggregation function, the default
	// selection is the fields used for "group-by", and the aggregation functions.
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(ptrgb.fields)+len(ptrgb.fns))
		for _, f := range ptrgb.fields {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	return selector.GroupBy(selector.Columns(ptrgb.fields...)...)
}

// PregnancyTestResultSelect is the builder for selecting fields of PregnancyTestResult entities.
type PregnancyTestResultSelect struct {
	*PregnancyTestResultQuery
	selector
	// intermediate query (i.e. traversal path).
	sql *sql.Selector
}

// Scan applies the selector query and scans the result into the given value.
func (ptrs *PregnancyTestResultSelect) Scan(ctx context.Context, v interface{}) error {
	if err := ptrs.prepareQuery(ctx); err != nil {
		return err
	}
	ptrs.sql = ptrs.PregnancyTestResultQuery.sqlQuery(ctx)
	return ptrs.sqlScan(ctx, v)
}

func (ptrs *PregnancyTestResultSelect) sqlScan(ctx context.Context, v interface{}) error {
	rows := &sql.Rows{}
	query, args := ptrs.sql.Query()
	if err := ptrs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
