// Code generated by entc, DO NOT EDIT.

package ent

import (
	"cattleai/ent/pregnancytestmethod"
	"fmt"
	"strings"

	"github.com/facebook/ent/dialect/sql"
)

// PregnancyTestMethod is the model entity for the PregnancyTestMethod schema.
type PregnancyTestMethod struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
}

// scanValues returns the types for scanning values from sql.Rows.
func (*PregnancyTestMethod) scanValues() []interface{} {
	return []interface{}{
		&sql.NullInt64{},  // id
		&sql.NullString{}, // name
	}
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the PregnancyTestMethod fields.
func (ptm *PregnancyTestMethod) assignValues(values ...interface{}) error {
	if m, n := len(values), len(pregnancytestmethod.Columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	value, ok := values[0].(*sql.NullInt64)
	if !ok {
		return fmt.Errorf("unexpected type %T for field id", value)
	}
	ptm.ID = int64(value.Int64)
	values = values[1:]
	if value, ok := values[0].(*sql.NullString); !ok {
		return fmt.Errorf("unexpected type %T for field name", values[0])
	} else if value.Valid {
		ptm.Name = value.String
	}
	return nil
}

// Update returns a builder for updating this PregnancyTestMethod.
// Note that, you need to call PregnancyTestMethod.Unwrap() before calling this method, if this PregnancyTestMethod
// was returned from a transaction, and the transaction was committed or rolled back.
func (ptm *PregnancyTestMethod) Update() *PregnancyTestMethodUpdateOne {
	return (&PregnancyTestMethodClient{config: ptm.config}).UpdateOne(ptm)
}

// Unwrap unwraps the entity that was returned from a transaction after it was closed,
// so that all next queries will be executed through the driver which created the transaction.
func (ptm *PregnancyTestMethod) Unwrap() *PregnancyTestMethod {
	tx, ok := ptm.config.driver.(*txDriver)
	if !ok {
		panic("ent: PregnancyTestMethod is not a transactional entity")
	}
	ptm.config.driver = tx.drv
	return ptm
}

// String implements the fmt.Stringer.
func (ptm *PregnancyTestMethod) String() string {
	var builder strings.Builder
	builder.WriteString("PregnancyTestMethod(")
	builder.WriteString(fmt.Sprintf("id=%v", ptm.ID))
	builder.WriteString(", name=")
	builder.WriteString(ptm.Name)
	builder.WriteByte(')')
	return builder.String()
}

// PregnancyTestMethods is a parsable slice of PregnancyTestMethod.
type PregnancyTestMethods []*PregnancyTestMethod

func (ptm PregnancyTestMethods) config(cfg config) {
	for _i := range ptm {
		ptm[_i].config = cfg
	}
}
