// Code generated by entc, DO NOT EDIT.

package ent

import (
	"cattleai/ent/predicate"
	"cattleai/ent/pregnancytesttype"
	"context"
	"errors"
	"fmt"
	"math"

	"github.com/facebook/ent/dialect/sql"
	"github.com/facebook/ent/dialect/sql/sqlgraph"
	"github.com/facebook/ent/schema/field"
)

// PregnancyTestTypeQuery is the builder for querying PregnancyTestType entities.
type PregnancyTestTypeQuery struct {
	config
	limit      *int
	offset     *int
	order      []OrderFunc
	unique     []string
	predicates []predicate.PregnancyTestType
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the builder.
func (pttq *PregnancyTestTypeQuery) Where(ps ...predicate.PregnancyTestType) *PregnancyTestTypeQuery {
	pttq.predicates = append(pttq.predicates, ps...)
	return pttq
}

// Limit adds a limit step to the query.
func (pttq *PregnancyTestTypeQuery) Limit(limit int) *PregnancyTestTypeQuery {
	pttq.limit = &limit
	return pttq
}

// Offset adds an offset step to the query.
func (pttq *PregnancyTestTypeQuery) Offset(offset int) *PregnancyTestTypeQuery {
	pttq.offset = &offset
	return pttq
}

// Order adds an order step to the query.
func (pttq *PregnancyTestTypeQuery) Order(o ...OrderFunc) *PregnancyTestTypeQuery {
	pttq.order = append(pttq.order, o...)
	return pttq
}

// First returns the first PregnancyTestType entity in the query. Returns *NotFoundError when no pregnancytesttype was found.
func (pttq *PregnancyTestTypeQuery) First(ctx context.Context) (*PregnancyTestType, error) {
	nodes, err := pttq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{pregnancytesttype.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (pttq *PregnancyTestTypeQuery) FirstX(ctx context.Context) *PregnancyTestType {
	node, err := pttq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first PregnancyTestType id in the query. Returns *NotFoundError when no id was found.
func (pttq *PregnancyTestTypeQuery) FirstID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = pttq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{pregnancytesttype.Label}
		return
	}
	return ids[0], nil
}

// FirstXID is like FirstID, but panics if an error occurs.
func (pttq *PregnancyTestTypeQuery) FirstXID(ctx context.Context) int64 {
	id, err := pttq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns the only PregnancyTestType entity in the query, returns an error if not exactly one entity was returned.
func (pttq *PregnancyTestTypeQuery) Only(ctx context.Context) (*PregnancyTestType, error) {
	nodes, err := pttq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{pregnancytesttype.Label}
	default:
		return nil, &NotSingularError{pregnancytesttype.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (pttq *PregnancyTestTypeQuery) OnlyX(ctx context.Context) *PregnancyTestType {
	node, err := pttq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID returns the only PregnancyTestType id in the query, returns an error if not exactly one id was returned.
func (pttq *PregnancyTestTypeQuery) OnlyID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = pttq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{pregnancytesttype.Label}
	default:
		err = &NotSingularError{pregnancytesttype.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (pttq *PregnancyTestTypeQuery) OnlyIDX(ctx context.Context) int64 {
	id, err := pttq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of PregnancyTestTypes.
func (pttq *PregnancyTestTypeQuery) All(ctx context.Context) ([]*PregnancyTestType, error) {
	if err := pttq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return pttq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (pttq *PregnancyTestTypeQuery) AllX(ctx context.Context) []*PregnancyTestType {
	nodes, err := pttq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of PregnancyTestType ids.
func (pttq *PregnancyTestTypeQuery) IDs(ctx context.Context) ([]int64, error) {
	var ids []int64
	if err := pttq.Select(pregnancytesttype.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (pttq *PregnancyTestTypeQuery) IDsX(ctx context.Context) []int64 {
	ids, err := pttq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (pttq *PregnancyTestTypeQuery) Count(ctx context.Context) (int, error) {
	if err := pttq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return pttq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (pttq *PregnancyTestTypeQuery) CountX(ctx context.Context) int {
	count, err := pttq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (pttq *PregnancyTestTypeQuery) Exist(ctx context.Context) (bool, error) {
	if err := pttq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return pttq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (pttq *PregnancyTestTypeQuery) ExistX(ctx context.Context) bool {
	exist, err := pttq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the query builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (pttq *PregnancyTestTypeQuery) Clone() *PregnancyTestTypeQuery {
	return &PregnancyTestTypeQuery{
		config:     pttq.config,
		limit:      pttq.limit,
		offset:     pttq.offset,
		order:      append([]OrderFunc{}, pttq.order...),
		unique:     append([]string{}, pttq.unique...),
		predicates: append([]predicate.PregnancyTestType{}, pttq.predicates...),
		// clone intermediate query.
		sql:  pttq.sql.Clone(),
		path: pttq.path,
	}
}

// GroupBy used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Name string `json:"name,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.PregnancyTestType.Query().
//		GroupBy(pregnancytesttype.FieldName).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
//
func (pttq *PregnancyTestTypeQuery) GroupBy(field string, fields ...string) *PregnancyTestTypeGroupBy {
	group := &PregnancyTestTypeGroupBy{config: pttq.config}
	group.fields = append([]string{field}, fields...)
	group.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := pttq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return pttq.sqlQuery(), nil
	}
	return group
}

// Select one or more fields from the given query.
//
// Example:
//
//	var v []struct {
//		Name string `json:"name,omitempty"`
//	}
//
//	client.PregnancyTestType.Query().
//		Select(pregnancytesttype.FieldName).
//		Scan(ctx, &v)
//
func (pttq *PregnancyTestTypeQuery) Select(field string, fields ...string) *PregnancyTestTypeSelect {
	selector := &PregnancyTestTypeSelect{config: pttq.config}
	selector.fields = append([]string{field}, fields...)
	selector.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := pttq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return pttq.sqlQuery(), nil
	}
	return selector
}

func (pttq *PregnancyTestTypeQuery) prepareQuery(ctx context.Context) error {
	if pttq.path != nil {
		prev, err := pttq.path(ctx)
		if err != nil {
			return err
		}
		pttq.sql = prev
	}
	return nil
}

func (pttq *PregnancyTestTypeQuery) sqlAll(ctx context.Context) ([]*PregnancyTestType, error) {
	var (
		nodes = []*PregnancyTestType{}
		_spec = pttq.querySpec()
	)
	_spec.ScanValues = func() []interface{} {
		node := &PregnancyTestType{config: pttq.config}
		nodes = append(nodes, node)
		values := node.scanValues()
		return values
	}
	_spec.Assign = func(values ...interface{}) error {
		if len(nodes) == 0 {
			return fmt.Errorf("ent: Assign called without calling ScanValues")
		}
		node := nodes[len(nodes)-1]
		return node.assignValues(values...)
	}
	if err := sqlgraph.QueryNodes(ctx, pttq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (pttq *PregnancyTestTypeQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := pttq.querySpec()
	return sqlgraph.CountNodes(ctx, pttq.driver, _spec)
}

func (pttq *PregnancyTestTypeQuery) sqlExist(ctx context.Context) (bool, error) {
	n, err := pttq.sqlCount(ctx)
	if err != nil {
		return false, fmt.Errorf("ent: check existence: %v", err)
	}
	return n > 0, nil
}

func (pttq *PregnancyTestTypeQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   pregnancytesttype.Table,
			Columns: pregnancytesttype.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt64,
				Column: pregnancytesttype.FieldID,
			},
		},
		From:   pttq.sql,
		Unique: true,
	}
	if ps := pttq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := pttq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := pttq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := pttq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector, pregnancytesttype.ValidColumn)
			}
		}
	}
	return _spec
}

func (pttq *PregnancyTestTypeQuery) sqlQuery() *sql.Selector {
	builder := sql.Dialect(pttq.driver.Dialect())
	t1 := builder.Table(pregnancytesttype.Table)
	selector := builder.Select(t1.Columns(pregnancytesttype.Columns...)...).From(t1)
	if pttq.sql != nil {
		selector = pttq.sql
		selector.Select(selector.Columns(pregnancytesttype.Columns...)...)
	}
	for _, p := range pttq.predicates {
		p(selector)
	}
	for _, p := range pttq.order {
		p(selector, pregnancytesttype.ValidColumn)
	}
	if offset := pttq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := pttq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// PregnancyTestTypeGroupBy is the builder for group-by PregnancyTestType entities.
type PregnancyTestTypeGroupBy struct {
	config
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (pttgb *PregnancyTestTypeGroupBy) Aggregate(fns ...AggregateFunc) *PregnancyTestTypeGroupBy {
	pttgb.fns = append(pttgb.fns, fns...)
	return pttgb
}

// Scan applies the group-by query and scan the result into the given value.
func (pttgb *PregnancyTestTypeGroupBy) Scan(ctx context.Context, v interface{}) error {
	query, err := pttgb.path(ctx)
	if err != nil {
		return err
	}
	pttgb.sql = query
	return pttgb.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (pttgb *PregnancyTestTypeGroupBy) ScanX(ctx context.Context, v interface{}) {
	if err := pttgb.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from group-by. It is only allowed when querying group-by with one field.
func (pttgb *PregnancyTestTypeGroupBy) Strings(ctx context.Context) ([]string, error) {
	if len(pttgb.fields) > 1 {
		return nil, errors.New("ent: PregnancyTestTypeGroupBy.Strings is not achievable when grouping more than 1 field")
	}
	var v []string
	if err := pttgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (pttgb *PregnancyTestTypeGroupBy) StringsX(ctx context.Context) []string {
	v, err := pttgb.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from group-by. It is only allowed when querying group-by with one field.
func (pttgb *PregnancyTestTypeGroupBy) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = pttgb.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{pregnancytesttype.Label}
	default:
		err = fmt.Errorf("ent: PregnancyTestTypeGroupBy.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (pttgb *PregnancyTestTypeGroupBy) StringX(ctx context.Context) string {
	v, err := pttgb.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from group-by. It is only allowed when querying group-by with one field.
func (pttgb *PregnancyTestTypeGroupBy) Ints(ctx context.Context) ([]int, error) {
	if len(pttgb.fields) > 1 {
		return nil, errors.New("ent: PregnancyTestTypeGroupBy.Ints is not achievable when grouping more than 1 field")
	}
	var v []int
	if err := pttgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (pttgb *PregnancyTestTypeGroupBy) IntsX(ctx context.Context) []int {
	v, err := pttgb.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from group-by. It is only allowed when querying group-by with one field.
func (pttgb *PregnancyTestTypeGroupBy) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = pttgb.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{pregnancytesttype.Label}
	default:
		err = fmt.Errorf("ent: PregnancyTestTypeGroupBy.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (pttgb *PregnancyTestTypeGroupBy) IntX(ctx context.Context) int {
	v, err := pttgb.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from group-by. It is only allowed when querying group-by with one field.
func (pttgb *PregnancyTestTypeGroupBy) Float64s(ctx context.Context) ([]float64, error) {
	if len(pttgb.fields) > 1 {
		return nil, errors.New("ent: PregnancyTestTypeGroupBy.Float64s is not achievable when grouping more than 1 field")
	}
	var v []float64
	if err := pttgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (pttgb *PregnancyTestTypeGroupBy) Float64sX(ctx context.Context) []float64 {
	v, err := pttgb.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from group-by. It is only allowed when querying group-by with one field.
func (pttgb *PregnancyTestTypeGroupBy) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = pttgb.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{pregnancytesttype.Label}
	default:
		err = fmt.Errorf("ent: PregnancyTestTypeGroupBy.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (pttgb *PregnancyTestTypeGroupBy) Float64X(ctx context.Context) float64 {
	v, err := pttgb.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from group-by. It is only allowed when querying group-by with one field.
func (pttgb *PregnancyTestTypeGroupBy) Bools(ctx context.Context) ([]bool, error) {
	if len(pttgb.fields) > 1 {
		return nil, errors.New("ent: PregnancyTestTypeGroupBy.Bools is not achievable when grouping more than 1 field")
	}
	var v []bool
	if err := pttgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (pttgb *PregnancyTestTypeGroupBy) BoolsX(ctx context.Context) []bool {
	v, err := pttgb.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from group-by. It is only allowed when querying group-by with one field.
func (pttgb *PregnancyTestTypeGroupBy) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = pttgb.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{pregnancytesttype.Label}
	default:
		err = fmt.Errorf("ent: PregnancyTestTypeGroupBy.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (pttgb *PregnancyTestTypeGroupBy) BoolX(ctx context.Context) bool {
	v, err := pttgb.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (pttgb *PregnancyTestTypeGroupBy) sqlScan(ctx context.Context, v interface{}) error {
	for _, f := range pttgb.fields {
		if !pregnancytesttype.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for group-by", f)}
		}
	}
	selector := pttgb.sqlQuery()
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := pttgb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (pttgb *PregnancyTestTypeGroupBy) sqlQuery() *sql.Selector {
	selector := pttgb.sql
	columns := make([]string, 0, len(pttgb.fields)+len(pttgb.fns))
	columns = append(columns, pttgb.fields...)
	for _, fn := range pttgb.fns {
		columns = append(columns, fn(selector, pregnancytesttype.ValidColumn))
	}
	return selector.Select(columns...).GroupBy(pttgb.fields...)
}

// PregnancyTestTypeSelect is the builder for select fields of PregnancyTestType entities.
type PregnancyTestTypeSelect struct {
	config
	fields []string
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Scan applies the selector query and scan the result into the given value.
func (ptts *PregnancyTestTypeSelect) Scan(ctx context.Context, v interface{}) error {
	query, err := ptts.path(ctx)
	if err != nil {
		return err
	}
	ptts.sql = query
	return ptts.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (ptts *PregnancyTestTypeSelect) ScanX(ctx context.Context, v interface{}) {
	if err := ptts.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from selector. It is only allowed when selecting one field.
func (ptts *PregnancyTestTypeSelect) Strings(ctx context.Context) ([]string, error) {
	if len(ptts.fields) > 1 {
		return nil, errors.New("ent: PregnancyTestTypeSelect.Strings is not achievable when selecting more than 1 field")
	}
	var v []string
	if err := ptts.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (ptts *PregnancyTestTypeSelect) StringsX(ctx context.Context) []string {
	v, err := ptts.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from selector. It is only allowed when selecting one field.
func (ptts *PregnancyTestTypeSelect) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = ptts.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{pregnancytesttype.Label}
	default:
		err = fmt.Errorf("ent: PregnancyTestTypeSelect.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (ptts *PregnancyTestTypeSelect) StringX(ctx context.Context) string {
	v, err := ptts.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from selector. It is only allowed when selecting one field.
func (ptts *PregnancyTestTypeSelect) Ints(ctx context.Context) ([]int, error) {
	if len(ptts.fields) > 1 {
		return nil, errors.New("ent: PregnancyTestTypeSelect.Ints is not achievable when selecting more than 1 field")
	}
	var v []int
	if err := ptts.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (ptts *PregnancyTestTypeSelect) IntsX(ctx context.Context) []int {
	v, err := ptts.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from selector. It is only allowed when selecting one field.
func (ptts *PregnancyTestTypeSelect) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = ptts.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{pregnancytesttype.Label}
	default:
		err = fmt.Errorf("ent: PregnancyTestTypeSelect.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (ptts *PregnancyTestTypeSelect) IntX(ctx context.Context) int {
	v, err := ptts.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from selector. It is only allowed when selecting one field.
func (ptts *PregnancyTestTypeSelect) Float64s(ctx context.Context) ([]float64, error) {
	if len(ptts.fields) > 1 {
		return nil, errors.New("ent: PregnancyTestTypeSelect.Float64s is not achievable when selecting more than 1 field")
	}
	var v []float64
	if err := ptts.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (ptts *PregnancyTestTypeSelect) Float64sX(ctx context.Context) []float64 {
	v, err := ptts.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from selector. It is only allowed when selecting one field.
func (ptts *PregnancyTestTypeSelect) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = ptts.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{pregnancytesttype.Label}
	default:
		err = fmt.Errorf("ent: PregnancyTestTypeSelect.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (ptts *PregnancyTestTypeSelect) Float64X(ctx context.Context) float64 {
	v, err := ptts.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from selector. It is only allowed when selecting one field.
func (ptts *PregnancyTestTypeSelect) Bools(ctx context.Context) ([]bool, error) {
	if len(ptts.fields) > 1 {
		return nil, errors.New("ent: PregnancyTestTypeSelect.Bools is not achievable when selecting more than 1 field")
	}
	var v []bool
	if err := ptts.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (ptts *PregnancyTestTypeSelect) BoolsX(ctx context.Context) []bool {
	v, err := ptts.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from selector. It is only allowed when selecting one field.
func (ptts *PregnancyTestTypeSelect) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = ptts.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{pregnancytesttype.Label}
	default:
		err = fmt.Errorf("ent: PregnancyTestTypeSelect.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (ptts *PregnancyTestTypeSelect) BoolX(ctx context.Context) bool {
	v, err := ptts.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (ptts *PregnancyTestTypeSelect) sqlScan(ctx context.Context, v interface{}) error {
	for _, f := range ptts.fields {
		if !pregnancytesttype.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for selection", f)}
		}
	}
	rows := &sql.Rows{}
	query, args := ptts.sqlQuery().Query()
	if err := ptts.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (ptts *PregnancyTestTypeSelect) sqlQuery() sql.Querier {
	selector := ptts.sql
	selector.Select(selector.Columns(ptts.fields...)...)
	return selector
}
