// Code generated by ent, DO NOT EDIT.

package ent

import (
	"cattleai/ent/predicate"
	"cattleai/ent/treatmentstate"
	"context"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// TreatmentStateQuery is the builder for querying TreatmentState entities.
type TreatmentStateQuery struct {
	config
	limit      *int
	offset     *int
	unique     *bool
	order      []OrderFunc
	fields     []string
	predicates []predicate.TreatmentState
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the TreatmentStateQuery builder.
func (tsq *TreatmentStateQuery) Where(ps ...predicate.TreatmentState) *TreatmentStateQuery {
	tsq.predicates = append(tsq.predicates, ps...)
	return tsq
}

// Limit adds a limit step to the query.
func (tsq *TreatmentStateQuery) Limit(limit int) *TreatmentStateQuery {
	tsq.limit = &limit
	return tsq
}

// Offset adds an offset step to the query.
func (tsq *TreatmentStateQuery) Offset(offset int) *TreatmentStateQuery {
	tsq.offset = &offset
	return tsq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (tsq *TreatmentStateQuery) Unique(unique bool) *TreatmentStateQuery {
	tsq.unique = &unique
	return tsq
}

// Order adds an order step to the query.
func (tsq *TreatmentStateQuery) Order(o ...OrderFunc) *TreatmentStateQuery {
	tsq.order = append(tsq.order, o...)
	return tsq
}

// First returns the first TreatmentState entity from the query.
// Returns a *NotFoundError when no TreatmentState was found.
func (tsq *TreatmentStateQuery) First(ctx context.Context) (*TreatmentState, error) {
	nodes, err := tsq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{treatmentstate.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (tsq *TreatmentStateQuery) FirstX(ctx context.Context) *TreatmentState {
	node, err := tsq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first TreatmentState ID from the query.
// Returns a *NotFoundError when no TreatmentState ID was found.
func (tsq *TreatmentStateQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = tsq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{treatmentstate.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (tsq *TreatmentStateQuery) FirstIDX(ctx context.Context) int {
	id, err := tsq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single TreatmentState entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one TreatmentState entity is found.
// Returns a *NotFoundError when no TreatmentState entities are found.
func (tsq *TreatmentStateQuery) Only(ctx context.Context) (*TreatmentState, error) {
	nodes, err := tsq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{treatmentstate.Label}
	default:
		return nil, &NotSingularError{treatmentstate.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (tsq *TreatmentStateQuery) OnlyX(ctx context.Context) *TreatmentState {
	node, err := tsq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only TreatmentState ID in the query.
// Returns a *NotSingularError when more than one TreatmentState ID is found.
// Returns a *NotFoundError when no entities are found.
func (tsq *TreatmentStateQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = tsq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{treatmentstate.Label}
	default:
		err = &NotSingularError{treatmentstate.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (tsq *TreatmentStateQuery) OnlyIDX(ctx context.Context) int {
	id, err := tsq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of TreatmentStates.
func (tsq *TreatmentStateQuery) All(ctx context.Context) ([]*TreatmentState, error) {
	if err := tsq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return tsq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (tsq *TreatmentStateQuery) AllX(ctx context.Context) []*TreatmentState {
	nodes, err := tsq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of TreatmentState IDs.
func (tsq *TreatmentStateQuery) IDs(ctx context.Context) ([]int, error) {
	var ids []int
	if err := tsq.Select(treatmentstate.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (tsq *TreatmentStateQuery) IDsX(ctx context.Context) []int {
	ids, err := tsq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (tsq *TreatmentStateQuery) Count(ctx context.Context) (int, error) {
	if err := tsq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return tsq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (tsq *TreatmentStateQuery) CountX(ctx context.Context) int {
	count, err := tsq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (tsq *TreatmentStateQuery) Exist(ctx context.Context) (bool, error) {
	if err := tsq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return tsq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (tsq *TreatmentStateQuery) ExistX(ctx context.Context) bool {
	exist, err := tsq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the TreatmentStateQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (tsq *TreatmentStateQuery) Clone() *TreatmentStateQuery {
	if tsq == nil {
		return nil
	}
	return &TreatmentStateQuery{
		config:     tsq.config,
		limit:      tsq.limit,
		offset:     tsq.offset,
		order:      append([]OrderFunc{}, tsq.order...),
		predicates: append([]predicate.TreatmentState{}, tsq.predicates...),
		// clone intermediate query.
		sql:    tsq.sql.Clone(),
		path:   tsq.path,
		unique: tsq.unique,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Name string `json:"name,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.TreatmentState.Query().
//		GroupBy(treatmentstate.FieldName).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (tsq *TreatmentStateQuery) GroupBy(field string, fields ...string) *TreatmentStateGroupBy {
	grbuild := &TreatmentStateGroupBy{config: tsq.config}
	grbuild.fields = append([]string{field}, fields...)
	grbuild.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := tsq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return tsq.sqlQuery(ctx), nil
	}
	grbuild.label = treatmentstate.Label
	grbuild.flds, grbuild.scan = &grbuild.fields, grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Name string `json:"name,omitempty"`
//	}
//
//	client.TreatmentState.Query().
//		Select(treatmentstate.FieldName).
//		Scan(ctx, &v)
func (tsq *TreatmentStateQuery) Select(fields ...string) *TreatmentStateSelect {
	tsq.fields = append(tsq.fields, fields...)
	selbuild := &TreatmentStateSelect{TreatmentStateQuery: tsq}
	selbuild.label = treatmentstate.Label
	selbuild.flds, selbuild.scan = &tsq.fields, selbuild.Scan
	return selbuild
}

func (tsq *TreatmentStateQuery) prepareQuery(ctx context.Context) error {
	for _, f := range tsq.fields {
		if !treatmentstate.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if tsq.path != nil {
		prev, err := tsq.path(ctx)
		if err != nil {
			return err
		}
		tsq.sql = prev
	}
	return nil
}

func (tsq *TreatmentStateQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*TreatmentState, error) {
	var (
		nodes = []*TreatmentState{}
		_spec = tsq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]interface{}, error) {
		return (*TreatmentState).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []interface{}) error {
		node := &TreatmentState{config: tsq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, tsq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (tsq *TreatmentStateQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := tsq.querySpec()
	_spec.Node.Columns = tsq.fields
	if len(tsq.fields) > 0 {
		_spec.Unique = tsq.unique != nil && *tsq.unique
	}
	return sqlgraph.CountNodes(ctx, tsq.driver, _spec)
}

func (tsq *TreatmentStateQuery) sqlExist(ctx context.Context) (bool, error) {
	n, err := tsq.sqlCount(ctx)
	if err != nil {
		return false, fmt.Errorf("ent: check existence: %w", err)
	}
	return n > 0, nil
}

func (tsq *TreatmentStateQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   treatmentstate.Table,
			Columns: treatmentstate.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: treatmentstate.FieldID,
			},
		},
		From:   tsq.sql,
		Unique: true,
	}
	if unique := tsq.unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := tsq.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, treatmentstate.FieldID)
		for i := range fields {
			if fields[i] != treatmentstate.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := tsq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := tsq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := tsq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := tsq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (tsq *TreatmentStateQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(tsq.driver.Dialect())
	t1 := builder.Table(treatmentstate.Table)
	columns := tsq.fields
	if len(columns) == 0 {
		columns = treatmentstate.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if tsq.sql != nil {
		selector = tsq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if tsq.unique != nil && *tsq.unique {
		selector.Distinct()
	}
	for _, p := range tsq.predicates {
		p(selector)
	}
	for _, p := range tsq.order {
		p(selector)
	}
	if offset := tsq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := tsq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// TreatmentStateGroupBy is the group-by builder for TreatmentState entities.
type TreatmentStateGroupBy struct {
	config
	selector
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (tsgb *TreatmentStateGroupBy) Aggregate(fns ...AggregateFunc) *TreatmentStateGroupBy {
	tsgb.fns = append(tsgb.fns, fns...)
	return tsgb
}

// Scan applies the group-by query and scans the result into the given value.
func (tsgb *TreatmentStateGroupBy) Scan(ctx context.Context, v interface{}) error {
	query, err := tsgb.path(ctx)
	if err != nil {
		return err
	}
	tsgb.sql = query
	return tsgb.sqlScan(ctx, v)
}

func (tsgb *TreatmentStateGroupBy) sqlScan(ctx context.Context, v interface{}) error {
	for _, f := range tsgb.fields {
		if !treatmentstate.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for group-by", f)}
		}
	}
	selector := tsgb.sqlQuery()
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := tsgb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (tsgb *TreatmentStateGroupBy) sqlQuery() *sql.Selector {
	selector := tsgb.sql.Select()
	aggregation := make([]string, 0, len(tsgb.fns))
	for _, fn := range tsgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	// If no columns were selected in a custom aggregation function, the default
	// selection is the fields used for "group-by", and the aggregation functions.
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(tsgb.fields)+len(tsgb.fns))
		for _, f := range tsgb.fields {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	return selector.GroupBy(selector.Columns(tsgb.fields...)...)
}

// TreatmentStateSelect is the builder for selecting fields of TreatmentState entities.
type TreatmentStateSelect struct {
	*TreatmentStateQuery
	selector
	// intermediate query (i.e. traversal path).
	sql *sql.Selector
}

// Scan applies the selector query and scans the result into the given value.
func (tss *TreatmentStateSelect) Scan(ctx context.Context, v interface{}) error {
	if err := tss.prepareQuery(ctx); err != nil {
		return err
	}
	tss.sql = tss.TreatmentStateQuery.sqlQuery(ctx)
	return tss.sqlScan(ctx, v)
}

func (tss *TreatmentStateSelect) sqlScan(ctx context.Context, v interface{}) error {
	rows := &sql.Rows{}
	query, args := tss.sql.Query()
	if err := tss.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
