// Code generated by entc, DO NOT EDIT.

package ent

import (
	"cattleai/ent/predicate"
	"cattleai/ent/warehousesetting"
	"context"
	"fmt"

	"github.com/facebook/ent/dialect/sql"
	"github.com/facebook/ent/dialect/sql/sqlgraph"
	"github.com/facebook/ent/schema/field"
)

// WarehouseSettingDelete is the builder for deleting a WarehouseSetting entity.
type WarehouseSettingDelete struct {
	config
	hooks      []Hook
	mutation   *WarehouseSettingMutation
	predicates []predicate.WarehouseSetting
}

// Where adds a new predicate to the delete builder.
func (wsd *WarehouseSettingDelete) Where(ps ...predicate.WarehouseSetting) *WarehouseSettingDelete {
	wsd.predicates = append(wsd.predicates, ps...)
	return wsd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (wsd *WarehouseSettingDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(wsd.hooks) == 0 {
		affected, err = wsd.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*WarehouseSettingMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			wsd.mutation = mutation
			affected, err = wsd.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(wsd.hooks) - 1; i >= 0; i-- {
			mut = wsd.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, wsd.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (wsd *WarehouseSettingDelete) ExecX(ctx context.Context) int {
	n, err := wsd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (wsd *WarehouseSettingDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: warehousesetting.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt64,
				Column: warehousesetting.FieldID,
			},
		},
	}
	if ps := wsd.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return sqlgraph.DeleteNodes(ctx, wsd.driver, _spec)
}

// WarehouseSettingDeleteOne is the builder for deleting a single WarehouseSetting entity.
type WarehouseSettingDeleteOne struct {
	wsd *WarehouseSettingDelete
}

// Exec executes the deletion query.
func (wsdo *WarehouseSettingDeleteOne) Exec(ctx context.Context) error {
	n, err := wsdo.wsd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{warehousesetting.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (wsdo *WarehouseSettingDeleteOne) ExecX(ctx context.Context) {
	wsdo.wsd.ExecX(ctx)
}
