// Code generated by entc, DO NOT EDIT.

package ent

import (
	"cattleai/ent/warehousesetting"
	"fmt"
	"strings"

	"github.com/facebook/ent/dialect/sql"
)

// WarehouseSetting is the model entity for the WarehouseSetting schema.
type WarehouseSetting struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Type holds the value of the "type" field.
	Type string `json:"type,omitempty"`
	// TenantId holds the value of the "tenantId" field.
	TenantId int64 `json:"tenantId,omitempty"`
	// TenantName holds the value of the "tenantName" field.
	TenantName string `json:"tenantName,omitempty"`
	// Remarks holds the value of the "remarks" field.
	Remarks string `json:"remarks,omitempty"`
	// CreatedAt holds the value of the "createdAt" field.
	CreatedAt int64 `json:"createdAt,omitempty"`
	// UpdatedAt holds the value of the "updatedAt" field.
	UpdatedAt int64 `json:"updatedAt,omitempty"`
	// Deleted holds the value of the "deleted" field.
	Deleted int `json:"deleted,omitempty"`
}

// scanValues returns the types for scanning values from sql.Rows.
func (*WarehouseSetting) scanValues() []interface{} {
	return []interface{}{
		&sql.NullInt64{},  // id
		&sql.NullString{}, // name
		&sql.NullString{}, // type
		&sql.NullInt64{},  // tenantId
		&sql.NullString{}, // tenantName
		&sql.NullString{}, // remarks
		&sql.NullInt64{},  // createdAt
		&sql.NullInt64{},  // updatedAt
		&sql.NullInt64{},  // deleted
	}
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the WarehouseSetting fields.
func (ws *WarehouseSetting) assignValues(values ...interface{}) error {
	if m, n := len(values), len(warehousesetting.Columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	value, ok := values[0].(*sql.NullInt64)
	if !ok {
		return fmt.Errorf("unexpected type %T for field id", value)
	}
	ws.ID = int64(value.Int64)
	values = values[1:]
	if value, ok := values[0].(*sql.NullString); !ok {
		return fmt.Errorf("unexpected type %T for field name", values[0])
	} else if value.Valid {
		ws.Name = value.String
	}
	if value, ok := values[1].(*sql.NullString); !ok {
		return fmt.Errorf("unexpected type %T for field type", values[1])
	} else if value.Valid {
		ws.Type = value.String
	}
	if value, ok := values[2].(*sql.NullInt64); !ok {
		return fmt.Errorf("unexpected type %T for field tenantId", values[2])
	} else if value.Valid {
		ws.TenantId = value.Int64
	}
	if value, ok := values[3].(*sql.NullString); !ok {
		return fmt.Errorf("unexpected type %T for field tenantName", values[3])
	} else if value.Valid {
		ws.TenantName = value.String
	}
	if value, ok := values[4].(*sql.NullString); !ok {
		return fmt.Errorf("unexpected type %T for field remarks", values[4])
	} else if value.Valid {
		ws.Remarks = value.String
	}
	if value, ok := values[5].(*sql.NullInt64); !ok {
		return fmt.Errorf("unexpected type %T for field createdAt", values[5])
	} else if value.Valid {
		ws.CreatedAt = value.Int64
	}
	if value, ok := values[6].(*sql.NullInt64); !ok {
		return fmt.Errorf("unexpected type %T for field updatedAt", values[6])
	} else if value.Valid {
		ws.UpdatedAt = value.Int64
	}
	if value, ok := values[7].(*sql.NullInt64); !ok {
		return fmt.Errorf("unexpected type %T for field deleted", values[7])
	} else if value.Valid {
		ws.Deleted = int(value.Int64)
	}
	return nil
}

// Update returns a builder for updating this WarehouseSetting.
// Note that, you need to call WarehouseSetting.Unwrap() before calling this method, if this WarehouseSetting
// was returned from a transaction, and the transaction was committed or rolled back.
func (ws *WarehouseSetting) Update() *WarehouseSettingUpdateOne {
	return (&WarehouseSettingClient{config: ws.config}).UpdateOne(ws)
}

// Unwrap unwraps the entity that was returned from a transaction after it was closed,
// so that all next queries will be executed through the driver which created the transaction.
func (ws *WarehouseSetting) Unwrap() *WarehouseSetting {
	tx, ok := ws.config.driver.(*txDriver)
	if !ok {
		panic("ent: WarehouseSetting is not a transactional entity")
	}
	ws.config.driver = tx.drv
	return ws
}

// String implements the fmt.Stringer.
func (ws *WarehouseSetting) String() string {
	var builder strings.Builder
	builder.WriteString("WarehouseSetting(")
	builder.WriteString(fmt.Sprintf("id=%v", ws.ID))
	builder.WriteString(", name=")
	builder.WriteString(ws.Name)
	builder.WriteString(", type=")
	builder.WriteString(ws.Type)
	builder.WriteString(", tenantId=")
	builder.WriteString(fmt.Sprintf("%v", ws.TenantId))
	builder.WriteString(", tenantName=")
	builder.WriteString(ws.TenantName)
	builder.WriteString(", remarks=")
	builder.WriteString(ws.Remarks)
	builder.WriteString(", createdAt=")
	builder.WriteString(fmt.Sprintf("%v", ws.CreatedAt))
	builder.WriteString(", updatedAt=")
	builder.WriteString(fmt.Sprintf("%v", ws.UpdatedAt))
	builder.WriteString(", deleted=")
	builder.WriteString(fmt.Sprintf("%v", ws.Deleted))
	builder.WriteByte(')')
	return builder.String()
}

// WarehouseSettings is a parsable slice of WarehouseSetting.
type WarehouseSettings []*WarehouseSetting

func (ws WarehouseSettings) config(cfg config) {
	for _i := range ws {
		ws[_i].config = cfg
	}
}
