// Code generated by ent, DO NOT EDIT.

package positionapi

const (
	// Label holds the string label denoting the positionapi type in the database.
	Label = "position_api"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldPositionId holds the string denoting the positionid field in the database.
	FieldPositionId = "position_id"
	// FieldApis holds the string denoting the apis field in the database.
	FieldApis = "apis"
	// Table holds the table name of the positionapi in the database.
	Table = "position_apis"
)

// Columns holds all SQL columns for positionapi fields.
var Columns = []string{
	FieldID,
	FieldPositionId,
	FieldApis,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}
