// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"github.com/facebook/ent/dialect/sql"
)

// BirthSurrounding is the predicate function for birthsurrounding builders.
type BirthSurrounding func(*sql.Selector)

// BreathRate is the predicate function for breathrate builders.
type BreathRate func(*sql.Selector)

// Category is the predicate function for category builders.
type Category func(*sql.Selector)

// Conf is the predicate function for conf builders.
type Conf func(*sql.Selector)

// Duty is the predicate function for duty builders.
type Duty func(*sql.Selector)

// Farm is the predicate function for farm builders.
type Farm func(*sql.Selector)

// HairState is the predicate function for hairstate builders.
type HairState func(*sql.Selector)

// Position is the predicate function for position builders.
type Position func(*sql.Selector)

// Shed is the predicate function for shed builders.
type Shed func(*sql.Selector)

// ShedCategory is the predicate function for shedcategory builders.
type ShedCategory func(*sql.Selector)

// ShedType is the predicate function for shedtype builders.
type ShedType func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)

// WindDirection is the predicate function for winddirection builders.
type WindDirection func(*sql.Selector)
